In [1]:
import matplotlib.pyplot as plt
import numpy as np 
import tensorflow as tf 
import cv2
import tensorflow_hub as hub

interpreter = tf.lite.Interpreter(model_path="lite-model_movenet_singlepose_lightning_3.tflite")
interpreter.allocate_tensors()

EDGES ={
    (0, 1): 'm',
    (0, 2): 'c',
    (1, 3): 'm',
    (2, 4): 'c',
    (0, 5): 'm',
    (0, 6): 'c',
    (5, 7): 'm',
    (7, 9): 'm',
    (6, 8): 'm',
    (8, 10): 'c',
    (5, 6): 'y',
    (5, 11): 'm',
    (6, 12): 'c',
    (11, 12): 'y',
    (11, 13): 'm',
    (13, 15): 'm',
    (12, 14): 'c',
    (14, 16): 'c'
}

def draw_keypoints(frame, keypoints, confidence_threshold):
    y,x,c = frame.shape
    shaped = np.squeeze(np.multiply(keypoints,[y,x,1]))
    
    for kp in shaped: 
        ky,kx, kp_conf = kp
        
        if kp_conf >confidence_threshold:
            
            cv2.circle(frame, (int(kx), int(ky)),4,(0,0,255),-1)
            

def draw_connections(frame, keypoints, edges, confidence_threshold):
    y,x,c = frame.shape
    
    shaped = np.squeeze(np.multiply(keypoints,[y,x,1]))
    
    for edge, color in edges.items():
        
        p1,p2 = edge
        y1,x1,c1 = shaped[p1]
        y2,x2,c2 = shaped[p2]        
        
        if (c1> confidence_threshold) & (c2> confidence_threshold):
            cv2.line(frame, (int(x1), int(y1)), (int(x2), int(y2)), (0,255,0), 2)

            
            
def loop_through_people(frame, keypoints_with_scores, edges, confidence_threshold):
    for person in keypoints_with_scores:
        draw_connections(frame, person, edges, confidence_threshold)
        draw_keypoints(frame, person, confidence_threshold)
        

model = hub.load('https://tfhub.dev/google/movenet/multipose/lightning/1')
movenet = model.signatures['serving_default']


OSError: SavedModel file does not exist at: C:\Users\ayush\AppData\Local\Temp\tfhub_modules\312f001449331ee3d410d758fccdc9945a65dbc3\{saved_model.pbtxt|saved_model.pb}

In [19]:
cap = cv2.VideoCapture(r"C:\Users\ayush\Desktop\Jump Rope Code\Video Dataset\JumpRope\v_JumpRope_g11_c01.avi")
while cap.isOpened():
    
    ret,frame = cap.read()
    
    
    #reshaping the image
    img = frame.copy()
    img= tf.image.resize_with_pad(np.expand_dims(img,axis=0),192,192)
    input_image = tf.cast(img,dtype=tf.float32)
    
    
    # setup input and output 
    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()
    
    
    # Make predictions
    
    interpreter.set_tensor(input_details[0]['index'],np.array(input_image))
    interpreter.invoke()
    keypoints_with_scores = interpreter.get_tensor(output_details[0]['index'])
    print(keypoints_with_scores)
    
    # Rendering 
    draw_connections(frame, keypoints_with_scores, EDGES, 0.4)
    draw_keypoints(frame, keypoints_with_scores, 0.4)
    
 
    
    cv2.imshow("Movenet", frame)
    
    if cv2.waitKey(50) & 0xFF==ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()

[[[[0.27045107 0.49954724 0.29624707]
   [0.2652306  0.49889967 0.3502472 ]
   [0.26270357 0.5033634  0.2674236 ]
   [0.26802653 0.49567276 0.27679256]
   [0.2683822  0.5055611  0.40296206]
   [0.32703325 0.4941525  0.38798586]
   [0.324004   0.5017691  0.5834718 ]
   [0.4001075  0.48931512 0.25848594]
   [0.40055776 0.49004325 0.26787493]
   [0.4540381  0.5031682  0.13589056]
   [0.45747095 0.47823554 0.1220974 ]
   [0.51800954 0.49803054 0.53981584]
   [0.5185368  0.49853683 0.46260503]
   [0.65000194 0.4961724  0.47673613]
   [0.65382934 0.49992234 0.4734681 ]
   [0.79156154 0.5022509  0.45558786]
   [0.7955916  0.50166    0.4484293 ]]]]
[[[[0.2721716  0.49617106 0.26561093]
   [0.26775324 0.49689326 0.35594845]
   [0.2641949  0.50137895 0.276997  ]
   [0.26914626 0.49616405 0.28459173]
   [0.26959923 0.50612485 0.41924855]
   [0.32948205 0.49448928 0.43255702]
   [0.3288326  0.49856436 0.46133983]
   [0.4049608  0.48917744 0.26666495]
   [0.4061817  0.48657915 0.28895137]
   [0.456

[[[[0.3395459  0.49742937 0.1773755 ]
   [0.3305176  0.4977648  0.21934661]
   [0.33178902 0.49703476 0.21990618]
   [0.34221324 0.50196874 0.2100625 ]
   [0.34326595 0.49835846 0.20800364]
   [0.38148695 0.49548563 0.2609172 ]
   [0.3847803  0.50026333 0.2806875 ]
   [0.4171756  0.4975215  0.16301765]
   [0.42584115 0.5064251  0.2052768 ]
   [0.4112707  0.49842423 0.1631466 ]
   [0.41635817 0.50834954 0.17545994]
   [0.5248527  0.50191283 0.38391566]
   [0.5273169  0.5036736  0.35812375]
   [0.6523275  0.49507755 0.41583863]
   [0.6544435  0.50134534 0.3977154 ]
   [0.7937917  0.49316233 0.44766915]
   [0.7989832  0.50255144 0.46872765]]]]
[[[[0.34731504 0.49338531 0.10079417]
   [0.33655584 0.49226934 0.1438721 ]
   [0.33875012 0.4915349  0.11957977]
   [0.34733626 0.49848545 0.13480042]
   [0.34913954 0.4965065  0.13805419]
   [0.3849551  0.4941194  0.19011843]
   [0.39056242 0.50466126 0.22383001]
   [0.39874184 0.4927387  0.11696116]
   [0.41384256 0.4996775  0.12848431]
   [0.395

[[[[0.3266815  0.49852014 0.23123564]
   [0.31462237 0.4957837  0.22936177]
   [0.31524393 0.49640936 0.27684346]
   [0.3260524  0.5033144  0.37820244]
   [0.32530987 0.504733   0.40924934]
   [0.3738541  0.50441295 0.3558896 ]
   [0.37251264 0.5092217  0.34830102]
   [0.407546   0.4969659  0.15730901]
   [0.4073441  0.50391906 0.16455469]
   [0.41246268 0.48844454 0.20824194]
   [0.41564342 0.5005714  0.16634029]
   [0.5195766  0.5062289  0.36900997]
   [0.5213571  0.5090134  0.386535  ]
   [0.64836264 0.49868935 0.438728  ]
   [0.64605176 0.50617516 0.42047268]
   [0.7875199  0.50432324 0.39011192]
   [0.7885909  0.5097763  0.48374385]]]]
[[[[0.3091601  0.49465197 0.35475957]
   [0.2977336  0.49327236 0.46411288]
   [0.29760054 0.49406382 0.3089993 ]
   [0.30250502 0.50227016 0.4512376 ]
   [0.30501354 0.50726104 0.36454266]
   [0.36091465 0.50641245 0.54461014]
   [0.35777956 0.50407434 0.56296074]
   [0.42269766 0.49746808 0.22245145]
   [0.4209083  0.49561977 0.18688837]
   [0.431

In [8]:
frame.shapebb

(480, 640, 3)

# Multipeople Model

In [21]:
cap = cv2.VideoCapture(r"C:\Users\ayush\Desktop\Jump Rope Code\Video Dataset\JumpRope\v_JumpRope_g12_c01.avi")
while cap.isOpened():
    ret, frame = cap.read()
    
    # Resize image
    img = frame.copy()
    img = tf.image.resize_with_pad(tf.expand_dims(img, axis=0), 640,480)
    input_img = tf.cast(img, dtype=tf.int32)
    
    # Detection section
    results = movenet(input_img)
    keypoints_with_scores = results['output_0'].numpy()[:,:,:51].reshape((6,17,3))
    
    # Render keypoints 
    loop_through_people(frame, keypoints_with_scores, EDGES, 0.3)
    
    cv2.imshow('Movenet Multipose', frame)
    
    if cv2.waitKey(10) & 0xFF==ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

In [12]:
frame.shape

(240, 320, 3)

In [8]:
model = hub.load("https://tfhub.dev/google/movenet/multipose/lightning/1")
movenet = model.signatures['serving_default']

####  Added movenet Thunder 


In [3]:
model = hub.load("https://tfhub.dev/google/movenet/singlepose/thunder/4")
movenet = model.signatures['serving_default']