# Task List (16-01-2023)

### step 1: load videos onto the system 

### step 2 : create a system where video can be parsed frame by frame by pressing a button 

### step 3 : apply human pose estimation on the one of the still images to see the performance of the human pose estimation models 

### step 4: apply opencv applications and lets see 


made use of the movenet lightning to see the human pose estimation 
https://tfhub.dev/google/lite-model/movenet/singlepose/lightning/3


Multipose network model

https://www.youtube.com/watch?v=KC7nJtBHBqg

In [1]:
import matplotlib.pyplot as plt
import numpy as np 
import tensorflow as tf 
import cv2
import tensorflow_hub as hub

In [2]:
import cv2

cap = cv2.VideoCapture(r"C:\Users\ayush\Desktop\Jump Rope Code\Media\JumpRopeChairAngle.mp4")
while not cap.isOpened():
    cap = cv2.VideoCapture(r"C:\Users\ayush\Desktop\Jump Rope Code\Media\JumpRopeChairAngle.mp4")
    cv2.waitKey(1000)
    print ("Wait for the header")

pos_frame = cap.get(cv2.CAP_PROP_POS_FRAMES)
while True:
    flag, frame = cap.read()
    if flag:
        # The frame is ready and already captured
        cv2.imshow('video', frame)
        pos_frame = cap.get(cv2.CAP_PROP_POS_FRAMES)
        print(str(pos_frame)+"frames")
    else:
        # The next frame is not ready, so we try to read it again
        cap.set(cv2.CAP_PROP_POS_FRAMES, pos_frame-1)
        print ("frame is not ready")
        # It is better to wait for a while for the next frame to be ready
        cv2.waitKey(1000)
        
    if cv2.waitKey(10) == 27:
        cv2.destroyAllWindows()
        break
    if cap.get(cv2.CAP_PROP_POS_FRAMES) == cap.get(cv2.CAP_PROP_FRAME_COUNT):
        # If the number of captured frames is equal to the total number of frames,
        # we stop
        cv2.destroyAllWindows()
        break

1.0frames
2.0frames
3.0frames
4.0frames
5.0frames
6.0frames
7.0frames
8.0frames
9.0frames
10.0frames
11.0frames
12.0frames
13.0frames
14.0frames
15.0frames
16.0frames
17.0frames
18.0frames
19.0frames
20.0frames
21.0frames
22.0frames
23.0frames
24.0frames
25.0frames
26.0frames
27.0frames
28.0frames
29.0frames
30.0frames
31.0frames
32.0frames
33.0frames
34.0frames
35.0frames
36.0frames
37.0frames
38.0frames
39.0frames
40.0frames
41.0frames
42.0frames
43.0frames
44.0frames
45.0frames
46.0frames
47.0frames
48.0frames
49.0frames
50.0frames
51.0frames
52.0frames
53.0frames
54.0frames
55.0frames
56.0frames
57.0frames
58.0frames
59.0frames
60.0frames
61.0frames
62.0frames
63.0frames
64.0frames
65.0frames
66.0frames
67.0frames
68.0frames
69.0frames
70.0frames
71.0frames
72.0frames
73.0frames
74.0frames
75.0frames
76.0frames
77.0frames
78.0frames
79.0frames
80.0frames
81.0frames
82.0frames
83.0frames
84.0frames
85.0frames
86.0frames
87.0frames
88.0frames
89.0frames
90.0frames
91.0frames
92.0fram

### Applying human pose estimation 

We will be applying skeleton based model for the openpose estimation 


In [3]:
interpreter = tf.lite.Interpreter(model_path="lite-model_movenet_singlepose_lightning_3.tflite")
interpreter.allocate_tensors()

In [4]:
EDGES ={
    (0, 1): 'm',
    (0, 2): 'c',
    (1, 3): 'm',
    (2, 4): 'c',
    (0, 5): 'm',
    (0, 6): 'c',
    (5, 7): 'm',
    (7, 9): 'm',
    (6, 8): 'm',
    (8, 10): 'c',
    (5, 6): 'y',
    (5, 11): 'm',
    (6, 12): 'c',
    (11, 12): 'y',
    (11, 13): 'm',
    (13, 15): 'm',
    (12, 14): 'c',
    (14, 16): 'c'
}

# Make Detections


In [13]:
cap = cv2.VideoCapture(r"C:\Users\ayush\Desktop\Jump Rope Code\Media\JumpRopeChairAngle.mp4")
while cap.isOpened():
    
    ret,frame = cap.read()
    
    
    #reshaping the image
    img = frame.copy()
    img= tf.image.resize_with_pad(np.expand_dims(img,axis=0),192,192)
    input_image = tf.cast(img,dtype=tf.float32)
    
    
    # setup input and output 
    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()
    
    
    # Make predictions
    
    interpreter.set_tensor(input_details[0]['index'],np.array(input_image))
    interpreter.invoke()
    keypoints_with_scores = interpreter.get_tensor(output_details[0]['index'])
    print(keypoints_with_scores)
    
    # Rendering 
    draw_connections(frame, keypoints_with_scores, EDGES, 0.4)
    draw_keypoints(frame, keypoints_with_scores, 0.4)
    
 
    
    cv2.imshow("Movenet", frame)
    
    if cv2.waitKey(1) & 0xFF==ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()

[[[[ 0.00490608  0.5382055   0.06264133]
   [-0.00735369  0.5750016   0.03279204]
   [-0.00886826  0.44227394  0.03595735]
   [-0.01888895  0.7429774   0.0106316 ]
   [-0.0266295   0.38730335  0.01018048]
   [ 0.00149063  0.7689208   0.15340227]
   [ 0.00116896  0.2610497   0.09632172]
   [ 0.3844546   0.8062341   0.23479927]
   [ 0.42038247  0.23699859  0.3496137 ]
   [ 0.50624454  0.82511663  0.076104  ]
   [ 0.4780807   0.2707948   0.07409493]
   [ 0.38700855  0.65166944  0.5274551 ]
   [ 0.39154705  0.41852367  0.6708058 ]
   [ 0.7768822   0.66092575  0.63224256]
   [ 0.7886681   0.45685586  0.48853207]
   [ 0.98824406  0.6887387   0.09807529]
   [ 0.99075747  0.44689295  0.05751707]]]]
[[[[ 6.06722385e-03  5.39283156e-01  6.80140406e-02]
   [-5.69739146e-03  5.75463533e-01  3.41084823e-02]
   [-8.01824126e-03  4.43426669e-01  3.17270532e-02]
   [-1.80773214e-02  7.44639158e-01  1.14218183e-02]
   [-2.65523698e-02  3.88253093e-01  9.61024128e-03]
   [ 8.90423195e-04  7.69783378e-01

[[[[ 6.4494386e-03  5.0450420e-01  7.6192498e-02]
   [-8.6461604e-03  5.7070559e-01  4.4191614e-02]
   [-1.1210780e-02  4.4139355e-01  4.2227555e-02]
   [-2.0979397e-02  7.2221655e-01  9.4696414e-03]
   [-2.9044885e-02  3.6978790e-01  7.6689408e-03]
   [-5.1560026e-04  7.5098050e-01  1.6157891e-01]
   [ 1.4276088e-03  2.3496327e-01  1.0588365e-01]
   [ 4.0528235e-01  7.9862416e-01  3.1043753e-01]
   [ 4.3798083e-01  2.3030162e-01  4.2790437e-01]
   [ 5.3952456e-01  7.9180735e-01  6.9488950e-02]
   [ 4.7964317e-01  2.5837985e-01  6.1317421e-02]
   [ 3.9338785e-01  6.5512925e-01  5.6803715e-01]
   [ 4.0702432e-01  4.0888762e-01  6.8894637e-01]
   [ 7.9175156e-01  6.7451406e-01  6.3085687e-01]
   [ 8.0431575e-01  4.5099181e-01  5.4379416e-01]
   [ 9.9180579e-01  7.0461845e-01  5.7401367e-02]
   [ 8.0855578e-01  4.5505032e-01  3.3035364e-02]]]]
[[[[ 0.00879439  0.53362006  0.08307305]
   [-0.00687468  0.5709238   0.05136105]
   [-0.00922692  0.44398373  0.04665469]
   [-0.02103342  0.72046

[[[[ 9.59418248e-03  4.29614961e-01  3.74671109e-02]
   [-5.09209989e-04  4.39773798e-01  2.62435935e-02]
   [ 4.74416930e-03  3.70841503e-01  2.51813326e-02]
   [-1.51372803e-02  6.64287925e-01  7.03420443e-03]
   [-6.35794131e-03  1.83814809e-01  2.70395409e-02]
   [-2.66372133e-03  7.25429058e-01  9.36095566e-02]
   [ 1.11851385e-02  1.97901458e-01  1.28927335e-01]
   [ 3.97466838e-01  8.00907731e-01  3.77616912e-01]
   [ 4.17940110e-01  1.98761344e-01  4.13134247e-01]
   [ 5.79927206e-01  7.77248561e-01  1.07036591e-01]
   [ 4.88355845e-01  2.40608364e-01  6.89842403e-02]
   [ 3.66356909e-01  6.67740047e-01  5.76764107e-01]
   [ 3.69188905e-01  4.35346484e-01  8.04092586e-01]
   [ 7.79618442e-01  6.60171866e-01  4.71179008e-01]
   [ 7.74810433e-01  4.66191500e-01  5.46446860e-01]
   [ 7.88689554e-01  6.01825356e-01  5.34429811e-02]
   [ 7.95515656e-01  4.77638125e-01  7.14646801e-02]]]]
[[[[ 0.01009319  0.4166578   0.06167085]
   [-0.0017099   0.4268682   0.03293618]
   [ 0.0023445

[[[[ 0.00224655  0.4996497   0.02750418]
   [-0.00125106  0.47838527  0.01433631]
   [ 0.00274886  0.43660843  0.01649868]
   [-0.0139834   0.6414342   0.00764946]
   [-0.0185891   0.35210782  0.00754761]
   [-0.00638534  0.6672003   0.06205047]
   [-0.00406537  0.267596    0.05859509]
   [ 0.15463527  0.77465546  0.18610966]
   [ 0.2818289   0.22423738  0.7388226 ]
   [ 0.48078614  0.7094593   0.3097711 ]
   [ 0.6615143   0.280217    0.4412793 ]
   [ 0.35417157  0.6220633   0.77796835]
   [ 0.35813245  0.41035268  0.8356439 ]
   [ 0.75082636  0.6433592   0.48764274]
   [ 0.7299346   0.45301148  0.6506152 ]
   [ 0.9885151   0.68230236  0.07764821]
   [ 0.9538938   0.44715047  0.28676865]]]]
[[[[ 0.00488042  0.48153028  0.0254877 ]
   [ 0.00224163  0.49524385  0.01419311]
   [ 0.00649505  0.43590528  0.01644587]
   [-0.00866684  0.814422    0.00662707]
   [-0.01916012  0.35065827  0.00580006]
   [-0.00816957  0.70491433  0.06266766]
   [-0.00622558  0.25082248  0.05721491]
   [ 0.222972

[[[[ 0.00634372  0.46336865  0.03294538]
   [ 0.00114482  0.49628448  0.03562924]
   [ 0.00226057  0.45206243  0.03430736]
   [-0.01607798  0.6160617   0.01269203]
   [-0.02001515  0.42237437  0.00915342]
   [ 0.00540477  0.6861602   0.16005522]
   [ 0.00710065  0.3013965   0.12298968]
   [ 0.15685871  0.7646427   0.74948615]
   [ 0.20614259  0.2551751   0.573313  ]
   [ 0.28146002  0.6229092   0.47561142]
   [ 0.42509842  0.27754083  0.7469031 ]
   [ 0.36968464  0.6181024   0.7295486 ]
   [ 0.3835017   0.404262    0.8823939 ]
   [ 0.8109615   0.7077776   0.7501287 ]
   [ 0.8115592   0.44945642  0.69060177]
   [ 0.9882986   0.6849923   0.04739352]
   [ 0.9870198   0.5157472   0.02947053]]]]
[[[[ 3.3539392e-03  5.1951969e-01  3.9663780e-02]
   [-9.9192956e-04  5.5360478e-01  3.7872929e-02]
   [-1.7046088e-03  5.0808889e-01  3.4409691e-02]
   [-1.9843588e-02  6.3320255e-01  1.1868008e-02]
   [-2.1461416e-02  4.2968160e-01  9.7187320e-03]
   [ 6.6937916e-03  6.9540739e-01  1.6528396e-01]


[[[[ 0.00793005  0.5291696   0.43737793]
   [-0.00631784  0.55655134  0.09488651]
   [-0.00679748  0.51113725  0.13579887]
   [ 0.01714116  0.5912621   0.6540991 ]
   [ 0.01608989  0.4840648   0.54715216]
   [ 0.13096341  0.6625392   0.90805554]
   [ 0.12914193  0.42747638  0.9535833 ]
   [ 0.27991614  0.75159156  0.7019113 ]
   [ 0.27605096  0.3453303   0.75233924]
   [ 0.40162265  0.74084985  0.5763937 ]
   [ 0.36589998  0.32161862  0.6993958 ]
   [ 0.44848952  0.62068725  0.8348423 ]
   [ 0.4483794   0.47288057  0.8287002 ]
   [ 0.77365184  0.64487743  0.7919601 ]
   [ 0.7621882   0.48408014  0.88692206]
   [ 0.99567884  0.6416719   0.03612995]
   [ 0.99937904  0.46146035  0.02350136]]]]
[[[[ 0.01340688  0.5364336   0.4264534 ]
   [-0.00307158  0.562531    0.12425303]
   [-0.00213297  0.52113706  0.19445476]
   [ 0.02081044  0.5972301   0.62364   ]
   [ 0.02112465  0.48800844  0.69057107]
   [ 0.13566737  0.6617256   0.891695  ]
   [ 0.13251019  0.4308738   0.95639825]
   [ 0.280775

[[[[0.16128586 0.517736   0.35792363]
   [0.14182864 0.5375138  0.65209955]
   [0.14068946 0.50251794 0.7210978 ]
   [0.16528028 0.56578356 0.65862674]
   [0.16186444 0.48250228 0.630283  ]
   [0.2531595  0.6196672  0.8981207 ]
   [0.25173032 0.42322966 0.92121625]
   [0.35414714 0.7018098  0.8974371 ]
   [0.35821992 0.35535353 0.8064606 ]
   [0.45750034 0.76335883 0.77642614]
   [0.4011708  0.2670177  0.74615866]
   [0.50799906 0.58814067 0.9189514 ]
   [0.5128616  0.4685142  0.93631184]
   [0.77936757 0.6131209  0.7938975 ]
   [0.76457304 0.4588817  0.87434936]
   [0.9842199  0.6114087  0.10171586]
   [0.9468132  0.48543346 0.6343087 ]]]]
[[[[0.1583426  0.513052   0.74414563]
   [0.14573485 0.5293125  0.77529764]
   [0.1453934  0.49801034 0.6555187 ]
   [0.16734403 0.55538034 0.7197212 ]
   [0.16761813 0.4771026  0.8430293 ]
   [0.25637975 0.61691505 0.9438953 ]
   [0.25773358 0.4206885  0.9331629 ]
   [0.35484093 0.69239295 0.6665572 ]
   [0.364207   0.3614672  0.79397124]
   [0.460

[[[[0.27474153 0.48528308 0.49123427]
   [0.2533807  0.5004177  0.45492306]
   [0.25158322 0.47147238 0.4419197 ]
   [0.2547571  0.51843774 0.69740325]
   [0.25523096 0.44746327 0.8400081 ]
   [0.3234489  0.5703176  0.91213167]
   [0.33127582 0.40791798 0.8770431 ]
   [0.41002357 0.6489108  0.7123287 ]
   [0.42550084 0.34430307 0.8202513 ]
   [0.47882026 0.67556417 0.8542887 ]
   [0.47887623 0.27602783 0.79630196]
   [0.53140956 0.56015927 0.8655939 ]
   [0.5382222  0.4683597  0.844218  ]
   [0.7421028  0.5864725  0.8988832 ]
   [0.7495147  0.4871866  0.88202834]
   [0.9616379  0.5893036  0.83935916]
   [0.9655881  0.49955982 0.7781062 ]]]]
[[[[0.28401223 0.49125826 0.5634424 ]
   [0.2630899  0.5049031  0.60545313]
   [0.2684382  0.47404858 0.4993835 ]
   [0.2633113  0.52051747 0.5567606 ]
   [0.26346996 0.44866067 0.86122406]
   [0.32322955 0.5668049  0.9003255 ]
   [0.33372825 0.40876442 0.89103645]
   [0.41084278 0.6472458  0.74450064]
   [0.4271968  0.35078904 0.8188398 ]
   [0.474

[[[[0.3712146  0.53779435 0.43287796]
   [0.3604824  0.5439818  0.40438908]
   [0.3617158  0.52612925 0.40604344]
   [0.34311038 0.54793024 0.5293052 ]
   [0.33656406 0.49912095 0.50073445]
   [0.3863053  0.5727901  0.6495342 ]
   [0.38778257 0.4502687  0.757484  ]
   [0.4863351  0.5953657  0.4189189 ]
   [0.50561965 0.43937612 0.3338304 ]
   [0.5278131  0.58238375 0.41707745]
   [0.5335215  0.54804343 0.34945533]
   [0.5630901  0.5582012  0.7240435 ]
   [0.56897926 0.49594042 0.75487024]
   [0.7473581  0.5733659  0.7866038 ]
   [0.7555951  0.49931535 0.6663556 ]
   [0.9065029  0.5541017  0.8042884 ]
   [0.95531416 0.50130457 0.5667601 ]]]]
[[[[0.36519015 0.5381011  0.47075847]
   [0.3541728  0.5428721  0.4960045 ]
   [0.35328826 0.5280961  0.44093043]
   [0.33891758 0.5492007  0.49853453]
   [0.3309203  0.5027726  0.40969533]
   [0.39134344 0.5767077  0.65395385]
   [0.38091716 0.454501   0.6425756 ]
   [0.4979473  0.586143   0.38335288]
   [0.5055126  0.4710793  0.3772381 ]
   [0.520

[[[[0.39883626 0.55725515 0.37398583]
   [0.38774383 0.56111676 0.40353203]
   [0.3856729  0.553555   0.3469261 ]
   [0.37553376 0.5531295  0.362714  ]
   [0.37360102 0.5382548  0.40319183]
   [0.4148655  0.5667335  0.35581386]
   [0.40622184 0.49042982 0.65077305]
   [0.51353323 0.56459475 0.24174495]
   [0.5049207  0.4631327  0.21919739]
   [0.5366756  0.59299374 0.33694875]
   [0.5388329  0.577177   0.39199677]
   [0.6122658  0.53563654 0.5026033 ]
   [0.6116973  0.52731174 0.5649048 ]
   [0.7571253  0.52193993 0.51564574]
   [0.7656119  0.54539144 0.59474593]
   [0.89783585 0.4978829  0.44069895]
   [0.92113775 0.5394294  0.6081382 ]]]]
[[[[0.40825936 0.55588454 0.3268306 ]
   [0.3998397  0.5613348  0.38194606]
   [0.39567757 0.55587476 0.42753   ]
   [0.38732252 0.5525478  0.29109314]
   [0.38108778 0.5318482  0.49244276]
   [0.42674872 0.56551224 0.4516113 ]
   [0.41485792 0.48723173 0.58625746]
   [0.5236189  0.57274854 0.24908046]
   [0.5139246  0.4744091  0.23195048]
   [0.541

[[[[0.41395903 0.5548871  0.2831246 ]
   [0.40359074 0.5413924  0.18884091]
   [0.4084992  0.5534957  0.4034523 ]
   [0.4013229  0.5145167  0.5223986 ]
   [0.41020882 0.54870546 0.5142442 ]
   [0.44503874 0.4706031  0.48719802]
   [0.4630526  0.56393194 0.41123202]
   [0.52110136 0.44794422 0.3011878 ]
   [0.54615045 0.6002688  0.26824328]
   [0.5364325  0.5424082  0.2566324 ]
   [0.5487053  0.60849285 0.4174028 ]
   [0.6278702  0.49503994 0.38371605]
   [0.62920296 0.55570793 0.55133986]
   [0.74702275 0.5114325  0.5564437 ]
   [0.75567615 0.55458164 0.5486396 ]
   [0.8803498  0.52093565 0.5129589 ]
   [0.90539956 0.55081797 0.5437569 ]]]]
[[[[0.4272468  0.5526346  0.22675702]
   [0.41911978 0.53660566 0.1765246 ]
   [0.4161795  0.555097   0.3306743 ]
   [0.41198575 0.51174307 0.56054676]
   [0.41623145 0.5514822  0.40704694]
   [0.46052748 0.46741387 0.49367288]
   [0.4683853  0.56718427 0.3287014 ]
   [0.52296245 0.44635424 0.2880574 ]
   [0.5445459  0.60273457 0.26755184]
   [0.525

[[[[0.44473252 0.54027915 0.23163828]
   [0.44071615 0.53072274 0.22653773]
   [0.4368083  0.54844964 0.23118867]
   [0.44151306 0.51709604 0.4932132 ]
   [0.43807933 0.55527914 0.43474546]
   [0.47930333 0.48414645 0.54118997]
   [0.47847015 0.57971525 0.5101813 ]
   [0.56408167 0.47357434 0.40740803]
   [0.55188334 0.59874237 0.27243918]
   [0.5707231  0.50073874 0.386949  ]
   [0.56679165 0.5884067  0.3579133 ]
   [0.64523304 0.5200062  0.49595016]
   [0.6365447  0.5819769  0.5611265 ]
   [0.7543447  0.5201367  0.54187584]
   [0.74305004 0.60122395 0.3647278 ]
   [0.8670707  0.5205545  0.54088247]
   [0.8418142  0.6169741  0.5965352 ]]]]
[[[[0.4414206  0.5485324  0.3419323 ]
   [0.43541905 0.53756326 0.28820044]
   [0.43519711 0.5521147  0.23810412]
   [0.4382136  0.5245814  0.54647243]
   [0.43781012 0.560115   0.39485174]
   [0.4809659  0.48940647 0.53819716]
   [0.4822199  0.5832379  0.51544046]
   [0.5633849  0.4736678  0.39705205]
   [0.55515164 0.59893996 0.31985423]
   [0.566

[[[[0.46586916 0.5919467  0.16896534]
   [0.46259603 0.5831331  0.198718  ]
   [0.45763624 0.59866947 0.18531117]
   [0.4651551  0.5583555  0.24859153]
   [0.46490932 0.5990376  0.23805669]
   [0.49870068 0.53672993 0.37982288]
   [0.50049067 0.6149582  0.4716188 ]
   [0.53714937 0.5022363  0.32035828]
   [0.5740034  0.63913655 0.27983275]
   [0.53477776 0.5083414  0.26886702]
   [0.58571553 0.6322243  0.29184514]
   [0.6513092  0.5551721  0.48476806]
   [0.6537497  0.6073868  0.48087442]
   [0.7508866  0.53887975 0.47181764]
   [0.7567234  0.6128181  0.50580156]
   [0.852898   0.5245501  0.5389823 ]
   [0.8519145  0.62200755 0.42926687]]]]
[[[[0.46289033 0.6053108  0.13708523]
   [0.45918986 0.5935581  0.19651814]
   [0.45569345 0.6097958  0.18872364]
   [0.45713028 0.5701783  0.51316786]
   [0.4599598  0.60619557 0.38866636]
   [0.49296612 0.53483975 0.37712672]
   [0.5003362  0.6191343  0.4547256 ]
   [0.5423572  0.50489306 0.32805336]
   [0.57042575 0.6431799  0.3549678 ]
   [0.533

[[[[0.4918284  0.6051074  0.20462498]
   [0.4918658  0.5969622  0.16621776]
   [0.4910413  0.61320895 0.22187608]
   [0.49355513 0.5777502  0.40375918]
   [0.49435198 0.62219757 0.40925014]
   [0.51444966 0.54462826 0.33385435]
   [0.5198003  0.63966984 0.45708844]
   [0.5489892  0.48919195 0.33496588]
   [0.5704222  0.6732363  0.18235524]
   [0.5303059  0.49605343 0.3119528 ]
   [0.5892528  0.6663178  0.37709057]
   [0.6430217  0.554425   0.44170702]
   [0.6475221  0.6166816  0.53984964]
   [0.73426    0.5479547  0.52134746]
   [0.74254626 0.6134032  0.58664495]
   [0.8336129  0.56767195 0.42363295]
   [0.83668196 0.6169871  0.5333313 ]]]]
[[[[0.48964438 0.60236424 0.2091014 ]
   [0.48626631 0.59216005 0.20794307]
   [0.48382038 0.610469   0.21412075]
   [0.48713505 0.5742841  0.34188595]
   [0.48781335 0.6181122  0.44195548]
   [0.5047399  0.5442236  0.4440503 ]
   [0.51798224 0.6374285  0.40481815]
   [0.5448947  0.48865616 0.3505123 ]
   [0.56696856 0.6722456  0.350535  ]
   [0.536

[[[[0.4781402  0.5551665  0.26379594]
   [0.46928233 0.54777884 0.27066162]
   [0.471878   0.5600042  0.21855897]
   [0.47476014 0.54108816 0.2867635 ]
   [0.47538853 0.5666979  0.34919423]
   [0.50950086 0.5282601  0.35276812]
   [0.51682687 0.5880467  0.31397116]
   [0.5170061  0.4989224  0.18078172]
   [0.5495789  0.60551155 0.2093732 ]
   [0.49650985 0.5068759  0.17200938]
   [0.52554625 0.59802324 0.23268831]
   [0.6515717  0.5380729  0.43244806]
   [0.6521285  0.5837039  0.45409146]
   [0.7487998  0.52532446 0.48807615]
   [0.75123954 0.6027628  0.36378708]
   [0.8501812  0.51863    0.46483767]
   [0.84798545 0.61214733 0.41038623]]]]
[[[[0.47623777 0.54605323 0.25907606]
   [0.47144467 0.5371376  0.2790419 ]
   [0.47342372 0.55845314 0.18227984]
   [0.47891197 0.5318395  0.36390045]
   [0.47977293 0.57275575 0.48571664]
   [0.5145473  0.5155696  0.37544194]
   [0.52319694 0.59425807 0.44551247]
   [0.540169   0.4870661  0.24241157]
   [0.5552156  0.6080203  0.24341202]
   [0.502

[[[[0.5033715  0.53647494 0.17512594]
   [0.49564406 0.5310885  0.24391517]
   [0.49345744 0.542319   0.21636967]
   [0.49284792 0.52435005 0.43146926]
   [0.49332413 0.5507942  0.38534364]
   [0.5152028  0.5020109  0.39625627]
   [0.52119434 0.57884264 0.4498569 ]
   [0.58365786 0.4800975  0.33495387]
   [0.5866434  0.6126652  0.45242533]
   [0.60065234 0.50261474 0.18892391]
   [0.60656977 0.60328645 0.39566797]
   [0.6611587  0.51725006 0.4736258 ]
   [0.65727794 0.5718004  0.5392449 ]
   [0.7481228  0.5153656  0.41157186]
   [0.74495786 0.5781049  0.44695333]
   [0.84124124 0.52614653 0.418502  ]
   [0.8404622  0.59757227 0.49068204]]]]
[[[[0.49768147 0.5367261  0.1986853 ]
   [0.4908944  0.5287857  0.26337343]
   [0.4902038  0.5407932  0.25137028]
   [0.48930475 0.51824546 0.43211338]
   [0.49044466 0.54828    0.4629975 ]
   [0.5121696  0.497323   0.41674644]
   [0.51971316 0.57750297 0.4568319 ]
   [0.57998747 0.48560655 0.31578347]
   [0.58595    0.610656   0.4128244 ]
   [0.599

[[[[0.48699272 0.54122525 0.30327347]
   [0.47870696 0.5269697  0.20686722]
   [0.4818241  0.5414956  0.23650026]
   [0.48284265 0.501712   0.40137902]
   [0.48270094 0.5416458  0.35088867]
   [0.52101654 0.4802793  0.44657263]
   [0.51963866 0.56841123 0.4112911 ]
   [0.5946858  0.45784926 0.28244796]
   [0.56962764 0.598575   0.23794271]
   [0.6067314  0.47829375 0.16720203]
   [0.6144985  0.585058   0.23985934]
   [0.6653951  0.51470125 0.47867298]
   [0.6610048  0.5669533  0.52581227]
   [0.75581753 0.51925313 0.43218946]
   [0.754864   0.5712286  0.50555515]
   [0.8485071  0.5269468  0.42827314]
   [0.85897887 0.57505214 0.55004585]]]]
[[[[0.48867607 0.534482   0.30726412]
   [0.48326227 0.52406925 0.22212207]
   [0.4837476  0.53677475 0.23916101]
   [0.4855451  0.499677   0.39294147]
   [0.48463994 0.5422538  0.37992576]
   [0.5192261  0.48070532 0.4558913 ]
   [0.51822066 0.5720514  0.42377168]
   [0.585038   0.45259792 0.23252422]
   [0.5549522  0.60308874 0.25472513]
   [0.575

[[[[0.49753913 0.5490154  0.22213346]
   [0.49221358 0.53510165 0.28879523]
   [0.49138653 0.5554529  0.2815074 ]
   [0.49172089 0.51406336 0.38706815]
   [0.49038517 0.560966   0.45047122]
   [0.52720934 0.49247128 0.3219126 ]
   [0.5189915  0.58470774 0.39478457]
   [0.5685987  0.47266573 0.29424247]
   [0.5784726  0.6075212  0.35028505]
   [0.5464731  0.48814195 0.21432784]
   [0.5829223  0.5954641  0.30970645]
   [0.66279054 0.51807976 0.45203042]
   [0.66158885 0.5727708  0.5414058 ]
   [0.75060165 0.5179689  0.41616157]
   [0.7492262  0.56980157 0.52026653]
   [0.8475046  0.52575254 0.44244635]
   [0.85521483 0.5719396  0.4961902 ]]]]
[[[[0.4871323  0.5384033  0.35932168]
   [0.481085   0.5414615  0.38628587]
   [0.4787093  0.5320603  0.44677922]
   [0.48047173 0.5445058  0.38881212]
   [0.47797439 0.5169978  0.32714364]
   [0.5138805  0.5569836  0.3049686 ]
   [0.5138404  0.5117865  0.25920266]
   [0.55125034 0.5895553  0.2561349 ]
   [0.5545215  0.48424193 0.21186835]
   [0.519

[[[[0.4556924  0.55223715 0.34343514]
   [0.44315776 0.55323005 0.38714463]
   [0.44442126 0.55066633 0.385293  ]
   [0.44582078 0.5472683  0.24316324]
   [0.4461624  0.5507869  0.4330843 ]
   [0.4942575  0.5200272  0.32944474]
   [0.49276727 0.5732695  0.3008691 ]
   [0.5401887  0.48559082 0.33326852]
   [0.56183475 0.58895236 0.3419509 ]
   [0.5475566  0.50222564 0.25099406]
   [0.5671939  0.58703357 0.24777155]
   [0.6414252  0.5239443  0.4932423 ]
   [0.64150983 0.5730587  0.54239607]
   [0.7464368  0.5234901  0.46394786]
   [0.7466215  0.5736406  0.5637398 ]
   [0.8557591  0.5185473  0.4234216 ]
   [0.867344   0.57244325 0.49446973]]]]
[[[[0.45200393 0.5546837  0.24843049]
   [0.43956947 0.558779   0.3597704 ]
   [0.4388531  0.54897827 0.39868602]
   [0.44088697 0.56247413 0.29931772]
   [0.43943557 0.5414986  0.33428866]
   [0.4881873  0.5517656  0.33655214]
   [0.48502347 0.550172   0.38151926]
   [0.5457441  0.50236523 0.23816413]
   [0.5611731  0.5689372  0.2220475 ]
   [0.538

[[[[0.44545102 0.5587102  0.28745   ]
   [0.44176388 0.54710305 0.28113073]
   [0.4400043  0.5607268  0.23607254]
   [0.44390982 0.5343612  0.46940175]
   [0.44293875 0.56753004 0.56230783]
   [0.4885443  0.5041139  0.620592  ]
   [0.492576   0.5944189  0.6461983 ]
   [0.562271   0.4840321  0.46083724]
   [0.5638156  0.61912024 0.4288046 ]
   [0.6296666  0.49493736 0.29937714]
   [0.594455   0.63019073 0.45529896]
   [0.6411816  0.52024925 0.47440657]
   [0.6447282  0.58181334 0.5509602 ]
   [0.74667823 0.5290557  0.43703538]
   [0.74692786 0.57435167 0.5695201 ]
   [0.85772836 0.5259784  0.5051988 ]
   [0.8658701  0.57249546 0.5555445 ]]]]
[[[[0.44782573 0.55608124 0.3197122 ]
   [0.44156706 0.54643464 0.21702325]
   [0.4421203  0.5584206  0.27540737]
   [0.44607633 0.5347155  0.46416616]
   [0.4449589  0.5638681  0.5363215 ]
   [0.490548   0.5040104  0.5873211 ]
   [0.4938386  0.5945823  0.61846083]
   [0.5643915  0.486796   0.4077914 ]
   [0.5633929  0.6184994  0.4148712 ]
   [0.629

[[[[0.44224066 0.5619314  0.23469213]
   [0.43668664 0.5503435  0.17007536]
   [0.43917748 0.56136024 0.3469184 ]
   [0.4415905  0.53418154 0.40572998]
   [0.44044107 0.5695586  0.5476136 ]
   [0.48380145 0.50371754 0.5361097 ]
   [0.4876582  0.58692265 0.50936395]
   [0.5280287  0.46115527 0.35918722]
   [0.5213712  0.64233124 0.36116064]
   [0.5342128  0.47799084 0.3764698 ]
   [0.51290745 0.63469166 0.3984732 ]
   [0.6368369  0.5189581  0.5586541 ]
   [0.6365894  0.58030736 0.6231122 ]
   [0.7445976  0.52880955 0.629858  ]
   [0.7401892  0.57500595 0.6183101 ]
   [0.85580945 0.5310098  0.35269853]
   [0.86329746 0.57077634 0.48591384]]]]
[[[[0.4422422  0.5591705  0.26092   ]
   [0.43732506 0.548689   0.17960416]
   [0.43686587 0.55905026 0.22907038]
   [0.44374442 0.53457206 0.43870005]
   [0.4410597  0.567695   0.53865635]
   [0.48407304 0.50619626 0.5552066 ]
   [0.48740393 0.58758736 0.5234107 ]
   [0.528546   0.46605933 0.35959932]
   [0.52252495 0.64592385 0.37042177]
   [0.535

[[[[0.41942856 0.55817664 0.22873421]
   [0.4119907  0.5466647  0.27143106]
   [0.413717   0.5606226  0.2377382 ]
   [0.41131842 0.5287565  0.3367246 ]
   [0.4176471  0.560427   0.3881524 ]
   [0.4492594  0.49098083 0.38603473]
   [0.45923817 0.5864035  0.44826454]
   [0.51429284 0.4594105  0.33498478]
   [0.5189376  0.6221343  0.27181995]
   [0.5290251  0.49431306 0.3897273 ]
   [0.510728   0.6091238  0.36043742]
   [0.6090334  0.51502955 0.55252457]
   [0.607061   0.57638186 0.5675533 ]
   [0.7128567  0.5236182  0.5343948 ]
   [0.71822226 0.5738667  0.52345943]
   [0.81457376 0.53699493 0.5462872 ]
   [0.82134366 0.5701474  0.6623798 ]]]]
[[[[0.43626565 0.5611     0.27937433]
   [0.42768377 0.55021447 0.23007488]
   [0.4350176  0.56603897 0.27348244]
   [0.4265034  0.52751005 0.30978218]
   [0.43599504 0.56986594 0.3363173 ]
   [0.46127695 0.49068725 0.4601301 ]
   [0.47597736 0.5900675  0.4269001 ]
   [0.52335876 0.4643209  0.29531404]
   [0.5223485  0.6286403  0.25892192]
   [0.527

[[[[0.45786285 0.558517   0.27854362]
   [0.45223516 0.5487641  0.14099333]
   [0.45582253 0.56639683 0.1947407 ]
   [0.4445594  0.51996887 0.33976427]
   [0.45011163 0.5569421  0.48322293]
   [0.47749007 0.48806387 0.4325807 ]
   [0.48694342 0.5875752  0.40735763]
   [0.5510986  0.47091627 0.29710627]
   [0.5290008  0.63646895 0.3108981 ]
   [0.5679867  0.49927863 0.2624245 ]
   [0.5343845  0.6233469  0.2733246 ]
   [0.6305931  0.51527816 0.40797606]
   [0.62906444 0.5835838  0.4896053 ]
   [0.7252988  0.52370185 0.5246072 ]
   [0.72662187 0.5736177  0.54570705]
   [0.8356346  0.53300744 0.34785944]
   [0.8318922  0.57741827 0.5533625 ]]]]
[[[[0.4543404  0.55111027 0.23854546]
   [0.44776112 0.53895044 0.19801351]
   [0.4496883  0.5532702  0.26750168]
   [0.448899   0.5194028  0.37420917]
   [0.45263326 0.5550548  0.6080422 ]
   [0.48759195 0.4920801  0.5316342 ]
   [0.4919359  0.57587343 0.51623654]
   [0.5504436  0.47209105 0.34913278]
   [0.54966474 0.6278883  0.31277943]
   [0.565

[[[[0.4711882  0.5354327  0.2714913 ]
   [0.46341437 0.5271678  0.15824443]
   [0.46528053 0.5416947  0.32393563]
   [0.46854135 0.50409985 0.43454117]
   [0.46888304 0.545309   0.5755376 ]
   [0.49720734 0.48122248 0.46277595]
   [0.5009937  0.5719484  0.4492216 ]
   [0.5460504  0.44997257 0.28353888]
   [0.53976303 0.62067246 0.30650052]
   [0.5510851  0.4750677  0.20340212]
   [0.5373343  0.59740174 0.3812337 ]
   [0.64446795 0.5123672  0.49388486]
   [0.6428876  0.56862307 0.5749687 ]
   [0.7455851  0.5164867  0.51335883]
   [0.7474527  0.57157296 0.6060136 ]
   [0.850096   0.52590245 0.45420483]
   [0.8565075  0.56435955 0.4277791 ]]]]
[[[[0.45610666 0.5374205  0.2503642 ]
   [0.45486206 0.53253865 0.21338403]
   [0.45415902 0.54467547 0.3649516 ]
   [0.45479858 0.51056516 0.44408655]
   [0.45630583 0.54903436 0.6617406 ]
   [0.49146932 0.48379725 0.5612935 ]
   [0.48946935 0.5740925  0.6225127 ]
   [0.5508986  0.46138632 0.32659876]
   [0.5489578  0.6114632  0.3133453 ]
   [0.571

[[[[0.4548852  0.53273886 0.250201  ]
   [0.44733566 0.5290594  0.15822302]
   [0.44709927 0.54165506 0.3391669 ]
   [0.4469515  0.514306   0.4153861 ]
   [0.44707853 0.54974264 0.6747143 ]
   [0.4847581  0.4860364  0.62676144]
   [0.48541638 0.57636553 0.6021458 ]
   [0.55743814 0.4758819  0.32428834]
   [0.5626879  0.60751176 0.40008813]
   [0.6091238  0.49693125 0.24474104]
   [0.60454994 0.596002   0.40397787]
   [0.6393606  0.51252246 0.6320293 ]
   [0.6350386  0.568451   0.61892956]
   [0.73650974 0.5237612  0.37247714]
   [0.73946273 0.57283896 0.56816745]
   [0.8524437  0.5311848  0.43246093]
   [0.8547952  0.56675225 0.41310427]]]]
[[[[0.45314234 0.53120697 0.2388121 ]
   [0.44473875 0.5264069  0.14393072]
   [0.4453989  0.539615   0.3608808 ]
   [0.44586548 0.51346004 0.39582726]
   [0.44550818 0.5482771  0.69137096]
   [0.4823836  0.49035048 0.6287283 ]
   [0.48555583 0.57793117 0.56359214]
   [0.5601152  0.46636558 0.34014896]
   [0.55902046 0.60382396 0.3032431 ]
   [0.608

[[[[0.50255954 0.54440844 0.23083277]
   [0.49089107 0.53944033 0.23000914]
   [0.4905779  0.5485153  0.27027735]
   [0.47914964 0.5325444  0.4497752 ]
   [0.48520595 0.5518236  0.36338025]
   [0.5164217  0.4998748  0.4186315 ]
   [0.5206307  0.5770504  0.40091994]
   [0.5951582  0.48499438 0.3022335 ]
   [0.59588885 0.59355843 0.3615332 ]
   [0.62123996 0.5174416  0.2649559 ]
   [0.6118251  0.5815791  0.33189955]
   [0.6638292  0.51922077 0.37079304]
   [0.6653929  0.5734551  0.51659954]
   [0.7648698  0.52282745 0.38065463]
   [0.76815933 0.5707198  0.5054114 ]
   [0.8549638  0.52093023 0.41915792]
   [0.8684435  0.5583428  0.5458325 ]]]]
[[[[0.49610096 0.5470793  0.17563859]
   [0.48244554 0.541969   0.26154727]
   [0.48291457 0.55238986 0.22152252]
   [0.47326466 0.5311425  0.43642563]
   [0.4808454  0.55829376 0.30835027]
   [0.5013907  0.49528968 0.4443167 ]
   [0.51223564 0.5842796  0.34880787]
   [0.58145845 0.4803544  0.34748808]
   [0.58266735 0.60294545 0.31128523]
   [0.619

[[[[0.45935953 0.5455133  0.25283003]
   [0.45171317 0.5331422  0.18544745]
   [0.4545946  0.5493423  0.33483225]
   [0.4592347  0.5168564  0.47092348]
   [0.45804882 0.5525843  0.45783013]
   [0.49990436 0.4920861  0.43116185]
   [0.49833307 0.5709871  0.3701264 ]
   [0.56172353 0.47454506 0.32851076]
   [0.5672754  0.59707654 0.38350233]
   [0.5773708  0.50487936 0.15301816]
   [0.58252466 0.6007042  0.4037928 ]
   [0.64512336 0.51708114 0.46669015]
   [0.6444755  0.5703524  0.51374304]
   [0.7390873  0.52411747 0.62214065]
   [0.742602   0.57455623 0.68249106]
   [0.8444378  0.5267812  0.357813  ]
   [0.85662144 0.56683636 0.4362662 ]]]]
[[[[0.4581486  0.54481614 0.24765049]
   [0.4510079  0.5320683  0.17121421]
   [0.45307517 0.54842156 0.34298396]
   [0.45916778 0.51632905 0.48137403]
   [0.4575687  0.5522537  0.4560327 ]
   [0.50117254 0.49242064 0.42791107]
   [0.49807972 0.5712874  0.37425107]
   [0.5611314  0.4756486  0.318135  ]
   [0.56524146 0.59863544 0.36942482]
   [0.573

[[[[0.46257573 0.5415458  0.24134108]
   [0.4560554  0.5341823  0.23579398]
   [0.45589623 0.5484203  0.22039185]
   [0.46408874 0.51797086 0.4185437 ]
   [0.4622445  0.5526414  0.545127  ]
   [0.49903584 0.4980173  0.45321584]
   [0.5020682  0.5756601  0.478503  ]
   [0.5669198  0.48051023 0.3332007 ]
   [0.5696446  0.60654694 0.407543  ]
   [0.56113017 0.49457857 0.25062594]
   [0.5799942  0.60219455 0.39267328]
   [0.6456449  0.51504993 0.42257175]
   [0.64711046 0.5755366  0.5576793 ]
   [0.7414501  0.5249368  0.607947  ]
   [0.744461   0.5739124  0.6578571 ]
   [0.8458554  0.52832663 0.37188455]
   [0.85217714 0.5693414  0.50588673]]]]
[[[[0.46411428 0.54191935 0.24534678]
   [0.45791632 0.534487   0.25682053]
   [0.4573986  0.5485856  0.23923644]
   [0.4664423  0.5166887  0.44363758]
   [0.4641115  0.55225253 0.57072496]
   [0.5029587  0.49554783 0.44962668]
   [0.50280666 0.5743958  0.50255615]
   [0.5689709  0.4808787  0.3261715 ]
   [0.57144964 0.6046003  0.4005086 ]
   [0.559

[[[[0.45528623 0.55053806 0.23915938]
   [0.45157647 0.53860116 0.20887303]
   [0.4532104  0.5560003  0.3042589 ]
   [0.4584319  0.52728766 0.4142888 ]
   [0.46157897 0.55968904 0.34284464]
   [0.49201816 0.50180626 0.45147598]
   [0.5007924  0.5752104  0.42311418]
   [0.5519693  0.47692367 0.37975648]
   [0.5686452  0.60352796 0.357282  ]
   [0.550622   0.4957599  0.2543672 ]
   [0.5818492  0.60842526 0.3599608 ]
   [0.64426035 0.5144141  0.4266509 ]
   [0.648458   0.5722916  0.5923451 ]
   [0.74698424 0.52666485 0.56947935]
   [0.7481725  0.5713028  0.546682  ]
   [0.8468722  0.52745986 0.393369  ]
   [0.85789895 0.5672924  0.4922097 ]]]]
[[[[0.45438182 0.5493685  0.24036264]
   [0.4506067  0.541581   0.18965557]
   [0.45218998 0.55490625 0.3098556 ]
   [0.4578112  0.5271082  0.41478768]
   [0.46088776 0.55957645 0.3486031 ]
   [0.49106014 0.5028363  0.46167168]
   [0.49953216 0.57484293 0.4344551 ]
   [0.5504796  0.47845197 0.37709755]
   [0.566409   0.6031106  0.3601238 ]
   [0.537

[[[[0.45951134 0.56206757 0.23162031]
   [0.44965455 0.5526369  0.21495628]
   [0.45325375 0.5674141  0.18726547]
   [0.4601968  0.53847325 0.38035676]
   [0.46193087 0.5685106  0.46854946]
   [0.49065524 0.5093651  0.41376925]
   [0.49880275 0.5836836  0.49324742]
   [0.5608262  0.47613165 0.40476027]
   [0.5798032  0.61187327 0.3309848 ]
   [0.5594039  0.4939505  0.2960019 ]
   [0.58547384 0.595737   0.4181803 ]
   [0.64116377 0.5168568  0.46634695]
   [0.646333   0.57558835 0.55980045]
   [0.74415797 0.53125274 0.59594077]
   [0.75246185 0.57124054 0.632527  ]
   [0.8472873  0.52904    0.38304847]
   [0.86505765 0.56879073 0.4242387 ]]]]
[[[[0.46931702 0.56679475 0.25887054]
   [0.46038264 0.5576223  0.21614502]
   [0.4626674  0.571033   0.29129335]
   [0.4678728  0.5378748  0.44962084]
   [0.46965548 0.5689964  0.5335996 ]
   [0.4975463  0.50766355 0.44686675]
   [0.5095077  0.5830636  0.3067831 ]
   [0.57226783 0.47823322 0.336548  ]
   [0.5849711  0.60836333 0.34604126]
   [0.575

[[[[0.44759393 0.559473   0.20006976]
   [0.4398081  0.54973376 0.24670818]
   [0.43881986 0.5617886  0.36330187]
   [0.44367954 0.53478265 0.2574218 ]
   [0.44151634 0.5684119  0.4957886 ]
   [0.48230356 0.5055343  0.30748942]
   [0.48229766 0.58992636 0.55089843]
   [0.5581098  0.4806772  0.38271293]
   [0.5471729  0.62344295 0.365775  ]
   [0.5635981  0.49246275 0.43770605]
   [0.57172966 0.60455036 0.35934907]
   [0.6381412  0.51542354 0.51030403]
   [0.6366705  0.5797082  0.56270117]
   [0.7463009  0.52754056 0.532669  ]
   [0.74610245 0.57346916 0.62031746]
   [0.85111845 0.5258768  0.42804632]
   [0.8706347  0.56685936 0.3818149 ]]]]
[[[[0.44988155 0.5599472  0.19855362]
   [0.43888247 0.54905146 0.19846325]
   [0.44075912 0.5623046  0.34881535]
   [0.44593924 0.5356642  0.2762936 ]
   [0.44292638 0.56991    0.50147086]
   [0.4828468  0.50697553 0.31849828]
   [0.48206732 0.5932081  0.5174711 ]
   [0.55546033 0.48552448 0.35046273]
   [0.54340875 0.6223148  0.33904132]
   [0.555

[[[[0.44610578 0.5606154  0.27589077]
   [0.43754846 0.5482427  0.22377287]
   [0.43950567 0.5637202  0.286963  ]
   [0.4401121  0.5383085  0.3934027 ]
   [0.4469158  0.5631955  0.4735832 ]
   [0.48107284 0.50191736 0.29085696]
   [0.4912685  0.5831914  0.4183992 ]
   [0.56087947 0.47881293 0.38125235]
   [0.5819123  0.59803224 0.29941455]
   [0.5579851  0.4949522  0.31301928]
   [0.5873591  0.5950017  0.4638503 ]
   [0.6409882  0.5151127  0.49434155]
   [0.6450811  0.56984055 0.5202024 ]
   [0.7410947  0.52421653 0.44273356]
   [0.74575865 0.5710972  0.59026855]
   [0.85337704 0.52349234 0.44772208]
   [0.8661997  0.56717145 0.37843642]]]]
[[[[0.447392   0.5611623  0.27212813]
   [0.43872488 0.5481208  0.23497991]
   [0.4410813  0.5642706  0.29201153]
   [0.44051892 0.53725004 0.39473438]
   [0.44848698 0.5637636  0.47369894]
   [0.48106027 0.50214493 0.28854296]
   [0.49174044 0.5827418  0.42558217]
   [0.5594527  0.47857034 0.38211662]
   [0.5824055  0.598601   0.30699357]
   [0.556

[[[[0.45421538 0.54802966 0.28460756]
   [0.44758305 0.5367845  0.14655587]
   [0.44754896 0.55453616 0.29297596]
   [0.45077878 0.52087766 0.28490123]
   [0.45502704 0.56309503 0.3359889 ]
   [0.49326953 0.48518822 0.4687018 ]
   [0.49791986 0.5856496  0.4857427 ]
   [0.56339383 0.46744645 0.27636692]
   [0.5711347  0.6046455  0.31344953]
   [0.5781213  0.50224817 0.29471466]
   [0.57616585 0.59270096 0.35666034]
   [0.65167147 0.5129237  0.517706  ]
   [0.65151626 0.5737248  0.5521928 ]
   [0.7399859  0.51993155 0.37846786]
   [0.74071276 0.572376   0.48724926]
   [0.852141   0.5261425  0.3446909 ]
   [0.85949814 0.5646926  0.3999011 ]]]]
[[[[0.46424708 0.5494599  0.26478875]
   [0.45627496 0.53893435 0.20821898]
   [0.45690405 0.55575    0.29497844]
   [0.45997673 0.5189185  0.2555928 ]
   [0.4610479  0.5625765  0.363616  ]
   [0.49469334 0.48402953 0.46458483]
   [0.5011221  0.58868814 0.47810206]
   [0.56471604 0.46680814 0.29873148]
   [0.57581294 0.609213   0.31498075]
   [0.576

[[[[0.45721862 0.5446479  0.2819268 ]
   [0.45133758 0.53797054 0.22805351]
   [0.45040855 0.5497223  0.3291139 ]
   [0.45435715 0.51882243 0.31794286]
   [0.453016   0.5535221  0.60029197]
   [0.4983396  0.4961387  0.45466113]
   [0.49442732 0.58143544 0.44346654]
   [0.5709349  0.47921574 0.30456597]
   [0.5597223  0.60372984 0.34725332]
   [0.5872872  0.48589993 0.36139455]
   [0.57194173 0.58114266 0.28480053]
   [0.6450135  0.5143151  0.53259856]
   [0.6426566  0.5731647  0.58628166]
   [0.73680496 0.5201143  0.52251625]
   [0.7384902  0.5698042  0.5921314 ]
   [0.8522475  0.5296606  0.4018529 ]
   [0.84982437 0.5682354  0.4368741 ]]]]
[[[[0.46246308 0.5522727  0.2964118 ]
   [0.4547246  0.542079   0.19095021]
   [0.45541704 0.5561077  0.32389948]
   [0.4590398  0.523985   0.37711966]
   [0.45777965 0.5567505  0.5406382 ]
   [0.5005857  0.49617696 0.39086914]
   [0.49524885 0.58247787 0.44599634]
   [0.5712639  0.47397372 0.32314613]
   [0.5627164  0.60155994 0.32295385]
   [0.597

[[[[0.47762305 0.5439681  0.41193864]
   [0.46877658 0.53612304 0.38331652]
   [0.4645973  0.54420614 0.26521224]
   [0.46956104 0.52463084 0.5600952 ]
   [0.46447933 0.5606961  0.40402573]
   [0.5097535  0.5008987  0.49519125]
   [0.49697757 0.5806748  0.47271943]
   [0.5460017  0.46376774 0.24981238]
   [0.53158885 0.60672    0.30184838]
   [0.5360235  0.46791086 0.43340847]
   [0.5324777  0.58616877 0.3116526 ]
   [0.6430524  0.50847286 0.49767685]
   [0.6403595  0.5664093  0.51996386]
   [0.7442467  0.518932   0.48345777]
   [0.74520195 0.5711497  0.6012853 ]
   [0.85548615 0.5262089  0.4075145 ]
   [0.86007637 0.5643531  0.45847428]]]]
[[[[0.46863836 0.54190093 0.28968805]
   [0.463528   0.5439213  0.3857864 ]
   [0.46071815 0.5515529  0.24312487]
   [0.46493328 0.5321963  0.54127556]
   [0.46270806 0.5626675  0.36491913]
   [0.5026076  0.5038463  0.44415393]
   [0.49471685 0.58518136 0.45837533]
   [0.5428748  0.4615949  0.23535354]
   [0.53295654 0.60979724 0.35135534]
   [0.532

[[[[0.4800975  0.5648964  0.3901438 ]
   [0.47271737 0.5693437  0.40054238]
   [0.472373   0.55825543 0.37121594]
   [0.47136295 0.5700213  0.26631698]
   [0.4693974  0.54477966 0.2939154 ]
   [0.51200056 0.58339703 0.39889777]
   [0.5047507  0.5182635  0.46661296]
   [0.5678128  0.5983677  0.2729946 ]
   [0.5728286  0.48391235 0.23482125]
   [0.5735666  0.58229864 0.28508925]
   [0.58257484 0.53039277 0.24719311]
   [0.6598257  0.5562073  0.42521375]
   [0.66429126 0.52921337 0.5238522 ]
   [0.7597477  0.5475426  0.40682828]
   [0.76188886 0.5444796  0.38490146]
   [0.8595519  0.53202504 0.48010865]
   [0.86454475 0.5451958  0.5503706 ]]]]
[[[[0.47252545 0.5696194  0.38925478]
   [0.4641325  0.57007706 0.3649485 ]
   [0.46501857 0.56096476 0.3794366 ]
   [0.46189138 0.56325376 0.28525   ]
   [0.46455595 0.54597557 0.4178295 ]
   [0.4996649  0.5693351  0.31764746]
   [0.49912044 0.52217454 0.4108233 ]
   [0.5640542  0.59374726 0.3142016 ]
   [0.5808002  0.5148293  0.20264816]
   [0.580

[[[[0.48161468 0.54884726 0.33580816]
   [0.4748512  0.5395757  0.25379372]
   [0.47525296 0.55516636 0.26130673]
   [0.4917119  0.51941854 0.23913679]
   [0.48222584 0.55765975 0.48157972]
   [0.5326311  0.49001598 0.2311389 ]
   [0.5305382  0.5702065  0.44059658]
   [0.5666507  0.4946055  0.22228189]
   [0.5463712  0.5874992  0.32171148]
   [0.51301867 0.50317043 0.10920204]
   [0.529147   0.60088307 0.31449488]
   [0.66478264 0.5170474  0.4504672 ]
   [0.6641317  0.5608605  0.42146012]
   [0.75914645 0.51921785 0.46419972]
   [0.75868094 0.567318   0.43508115]
   [0.8515508  0.5173508  0.3835318 ]
   [0.86850375 0.55445033 0.5135727 ]]]]
[[[[0.4764045  0.54824775 0.30001423]
   [0.47077733 0.5380604  0.23787521]
   [0.4651035  0.55400074 0.3058601 ]
   [0.48017132 0.5226408  0.36182287]
   [0.47151324 0.559802   0.5108816 ]
   [0.52800614 0.4891537  0.33264935]
   [0.5236381  0.5771681  0.43467754]
   [0.56795746 0.48697472 0.24168506]
   [0.5431873  0.5931443  0.30010286]
   [0.517

[[[[0.4675486  0.5285154  0.14204256]
   [0.4551983  0.51263547 0.157855  ]
   [0.45459276 0.5281478  0.29074785]
   [0.46232045 0.4995222  0.27513954]
   [0.46535942 0.5342595  0.25830016]
   [0.49100026 0.4922548  0.4175407 ]
   [0.4974533  0.56165826 0.4262699 ]
   [0.57683295 0.47743115 0.32625574]
   [0.5812468  0.5823487  0.33422947]
   [0.6002416  0.4807875  0.2227621 ]
   [0.609697   0.58210206 0.35255897]
   [0.64524686 0.513487   0.36855364]
   [0.65013033 0.567832   0.5129093 ]
   [0.73945236 0.5246675  0.47853035]
   [0.7429859  0.5688281  0.5375688 ]
   [0.8461129  0.52629507 0.40191063]
   [0.8593693  0.5665723  0.4175544 ]]]]
[[[[0.4537661  0.5208794  0.19585589]
   [0.4496715  0.51160645 0.20583424]
   [0.44680378 0.5255041  0.27238318]
   [0.45131275 0.49685967 0.25868043]
   [0.44881392 0.52882266 0.4756239 ]
   [0.4899106  0.4921838  0.50441325]
   [0.48305532 0.5585173  0.53689784]
   [0.5718845  0.4803884  0.40099812]
   [0.55765325 0.5793911  0.381779  ]
   [0.605

[[[[0.45445728 0.5384697  0.19599004]
   [0.44803804 0.531474   0.16919884]
   [0.44786045 0.5424629  0.28169972]
   [0.45691347 0.5192803  0.3820406 ]
   [0.4501317  0.548035   0.4670924 ]
   [0.49406716 0.49628282 0.38286886]
   [0.49077234 0.5739485  0.55188394]
   [0.57115424 0.4719299  0.28208593]
   [0.5422331  0.6035967  0.33593184]
   [0.58205295 0.4763214  0.45708728]
   [0.5661588  0.5854955  0.27578226]
   [0.6422487  0.5101341  0.58329403]
   [0.63999975 0.56931734 0.61405915]
   [0.7434892  0.51680005 0.40472344]
   [0.7451624  0.5707282  0.60852706]
   [0.85282844 0.521793   0.39693815]
   [0.86295885 0.5596428  0.4870075 ]]]]
[[[[0.4534557  0.5382403  0.2229164 ]
   [0.44785547 0.53047156 0.16875239]
   [0.44532105 0.5430327  0.26693475]
   [0.4570225  0.5166738  0.41585246]
   [0.44744623 0.54845506 0.4760727 ]
   [0.49505728 0.49410045 0.4170204 ]
   [0.4916528  0.57537633 0.5661192 ]
   [0.5711696  0.47111636 0.33086777]
   [0.549878   0.60476065 0.27809373]
   [0.587

[[[[0.471863   0.5458226  0.30824763]
   [0.46455395 0.54551125 0.25000602]
   [0.46046314 0.5411182  0.3408776 ]
   [0.4671898  0.54042137 0.25741497]
   [0.4664671  0.53579104 0.3747422 ]
   [0.5161121  0.52523357 0.27312157]
   [0.5122628  0.53254557 0.37607422]
   [0.5744252  0.54745597 0.19608018]
   [0.5774464  0.5754555  0.26346326]
   [0.5700724  0.5859254  0.3154844 ]
   [0.56942946 0.5887996  0.27561852]
   [0.66309106 0.5312481  0.3811006 ]
   [0.66611516 0.5425348  0.3907017 ]
   [0.7536491  0.5308608  0.548507  ]
   [0.7566422  0.54829794 0.4296455 ]
   [0.85480094 0.5254086  0.40844685]
   [0.8625757  0.54803956 0.41911536]]]]
[[[[0.47878617 0.5372193  0.34816545]
   [0.47065312 0.54367703 0.38466215]
   [0.4699101  0.53343165 0.34909585]
   [0.46611434 0.55051804 0.43920648]
   [0.47434506 0.5167089  0.4563503 ]
   [0.50596267 0.5686884  0.33163396]
   [0.51635826 0.4947458  0.37277472]
   [0.56369746 0.6062943  0.3046088 ]
   [0.56693745 0.49943185 0.24271078]
   [0.554

[[[[0.46704054 0.5442621  0.2554805 ]
   [0.45650572 0.5286763  0.21624765]
   [0.45784825 0.5468334  0.22209781]
   [0.4633541  0.50758344 0.37106073]
   [0.46362588 0.5459233  0.39566466]
   [0.51470053 0.4790296  0.42103535]
   [0.49918586 0.5790164  0.4673996 ]
   [0.57688034 0.46256638 0.28204608]
   [0.5653933  0.5976743  0.29461342]
   [0.5791198  0.46586865 0.242366  ]
   [0.5839409  0.5876684  0.27365315]
   [0.65787935 0.508657   0.53419495]
   [0.65502954 0.5689842  0.55154717]
   [0.7523796  0.5159336  0.39299452]
   [0.7524427  0.569575   0.53597647]
   [0.851942   0.51974845 0.34197706]
   [0.8608059  0.56131953 0.5225929 ]]]]
[[[[0.46884176 0.537281   0.20012747]
   [0.46091387 0.52536845 0.2040677 ]
   [0.45957917 0.5387796  0.22071642]
   [0.46332204 0.5086843  0.42087072]
   [0.4604081  0.54324204 0.39557084]
   [0.5076078  0.4892258  0.5083941 ]
   [0.5014374  0.57376826 0.4697377 ]
   [0.58962893 0.47950506 0.27714872]
   [0.5814835  0.5900777  0.38344812]
   [0.637

[[[[0.4738537  0.5327245  0.20596902]
   [0.4683083  0.52245325 0.21261576]
   [0.4653785  0.53575873 0.2636988 ]
   [0.47358322 0.5096146  0.5257032 ]
   [0.4660033  0.54463804 0.46952814]
   [0.5027369  0.48433825 0.43494433]
   [0.4920947  0.57626224 0.52925783]
   [0.57469827 0.46382293 0.2431622 ]
   [0.5270806  0.6048878  0.40352854]
   [0.5757837  0.47525376 0.41924876]
   [0.5460627  0.5787306  0.2670372 ]
   [0.6496002  0.50399965 0.53497857]
   [0.6469343  0.5620179  0.43894866]
   [0.74968076 0.51489264 0.40775812]
   [0.7490425  0.5655905  0.4905035 ]
   [0.8561239  0.52283204 0.3731749 ]
   [0.86177194 0.55561244 0.5133736 ]]]]
[[[[0.47449788 0.53186476 0.30990294]
   [0.466716   0.5266213  0.34154502]
   [0.46651256 0.5320195  0.32539687]
   [0.4682386  0.5161973  0.3013019 ]
   [0.4675897  0.5301603  0.4234366 ]
   [0.50746155 0.50520235 0.32569167]
   [0.49977773 0.5551705  0.33335343]
   [0.5789119  0.47786433 0.3024463 ]
   [0.5621078  0.55342406 0.18741263]
   [0.584

[[[[0.4895916  0.536025   0.34707078]
   [0.48297143 0.52625734 0.35468572]
   [0.4821038  0.5392941  0.30969715]
   [0.48749655 0.5150157  0.3470295 ]
   [0.4838382  0.53900796 0.4244186 ]
   [0.53623843 0.4858347  0.35442692]
   [0.523772   0.56713367 0.35640606]
   [0.5721686  0.4866383  0.2157057 ]
   [0.56122565 0.6087481  0.24837455]
   [0.52724004 0.50422716 0.14863819]
   [0.5386046  0.61363435 0.29081511]
   [0.6659344  0.5103964  0.45733815]
   [0.66399634 0.55808544 0.47788307]
   [0.75662464 0.5120419  0.40424326]
   [0.75789773 0.5625578  0.47396508]
   [0.85514617 0.5176652  0.4142243 ]
   [0.8654291  0.552564   0.54781413]]]]
[[[[0.5007204  0.52989113 0.30808425]
   [0.4914034  0.518065   0.31721705]
   [0.49099872 0.53530675 0.35568422]
   [0.50035256 0.5026273  0.35388365]
   [0.4977603  0.54100156 0.37472552]
   [0.55403125 0.48311424 0.37826678]
   [0.5412249  0.5689198  0.35207248]
   [0.58787286 0.48185763 0.27505025]
   [0.5546473  0.60670304 0.3077317 ]
   [0.502

[[[[0.48552674 0.5290429  0.27982786]
   [0.4807304  0.52020156 0.26331514]
   [0.4762978  0.5336621  0.28681767]
   [0.48191947 0.49816808 0.35428944]
   [0.4758502  0.5383892  0.40773663]
   [0.5238507  0.48218367 0.39842525]
   [0.50020945 0.568437   0.53176856]
   [0.5768312  0.46017247 0.2819785 ]
   [0.53173846 0.59758073 0.27520433]
   [0.5658802  0.4692275  0.35081235]
   [0.5447613  0.5718448  0.26907617]
   [0.6585218  0.5102031  0.5710145 ]
   [0.65502167 0.5640007  0.53784716]
   [0.75445    0.5186664  0.44139543]
   [0.7545123  0.5709994  0.546729  ]
   [0.85303825 0.5173237  0.34521484]
   [0.8683249  0.55682594 0.47861868]]]]
[[[[0.48871022 0.5286768  0.32122865]
   [0.4836272  0.52498734 0.27076462]
   [0.48351187 0.5373396  0.30009443]
   [0.48754543 0.50739706 0.4623676 ]
   [0.48042762 0.54482156 0.45061883]
   [0.5348928  0.48967072 0.4133384 ]
   [0.5082372  0.5768199  0.5694088 ]
   [0.57245016 0.46691713 0.29364002]
   [0.53187084 0.597211   0.3042809 ]
   [0.545

[[[[0.46293312 0.5326262  0.26434177]
   [0.46126387 0.523551   0.21009934]
   [0.45650944 0.53625715 0.29144612]
   [0.46525216 0.5064606  0.48142937]
   [0.4625014  0.54873145 0.5389499 ]
   [0.50636566 0.47836393 0.48993754]
   [0.51002187 0.5816884  0.43104076]
   [0.56054884 0.4789438  0.30211937]
   [0.56919557 0.6138607  0.32892537]
   [0.53858054 0.49607763 0.32845026]
   [0.58410096 0.59088326 0.30954117]
   [0.65587765 0.50779796 0.5806751 ]
   [0.65477395 0.56328666 0.5098642 ]
   [0.75563014 0.51199484 0.4217498 ]
   [0.7541663  0.56251824 0.42425513]
   [0.8545133  0.5215285  0.3813611 ]
   [0.86522496 0.5524842  0.5038636 ]]]]
[[[[0.45592892 0.53555477 0.2093    ]
   [0.45264995 0.5245676  0.1562325 ]
   [0.44883972 0.5379838  0.3204727 ]
   [0.45435283 0.5054667  0.42744267]
   [0.45007253 0.5451743  0.6390668 ]
   [0.49680233 0.48271725 0.47880533]
   [0.49932134 0.57950604 0.5698971 ]
   [0.5628111  0.48298603 0.3344634 ]
   [0.56564176 0.6098234  0.4221632 ]
   [0.584

[[[[0.45462248 0.53763425 0.24628589]
   [0.44999108 0.5316241  0.24568598]
   [0.44801742 0.5423271  0.28966534]
   [0.4577458  0.5156878  0.3998548 ]
   [0.452033   0.55058277 0.53461754]
   [0.49874634 0.4937986  0.46179774]
   [0.4944497  0.57435715 0.42327902]
   [0.5679208  0.47435722 0.37058526]
   [0.56702167 0.5964592  0.42092597]
   [0.56759185 0.48703963 0.4000845 ]
   [0.5970021  0.5891999  0.4342076 ]
   [0.64671016 0.5180839  0.46804166]
   [0.64806056 0.5703693  0.55427176]
   [0.73980117 0.5227089  0.39460546]
   [0.7419459  0.5715306  0.5170357 ]
   [0.84897673 0.524054   0.37549546]
   [0.8566052  0.5644346  0.45515686]]]]
[[[[0.4552492  0.5409243  0.2362677 ]
   [0.44769368 0.5328523  0.19029447]
   [0.4468099  0.5437709  0.27213153]
   [0.45504865 0.52140903 0.3576833 ]
   [0.45158955 0.54980737 0.4932186 ]
   [0.49275756 0.4996081  0.40864274]
   [0.49306637 0.57754874 0.44303608]
   [0.56760824 0.4760253  0.352826  ]
   [0.56102556 0.6012205  0.32013407]
   [0.560

[[[[0.46683154 0.538318   0.24503003]
   [0.46170807 0.52956516 0.2425316 ]
   [0.45925233 0.5419316  0.2930221 ]
   [0.47542167 0.52069354 0.40968943]
   [0.4624898  0.5479189  0.4131657 ]
   [0.5045537  0.49771127 0.35572115]
   [0.48998103 0.57114756 0.49222597]
   [0.58070946 0.4765743  0.28958827]
   [0.5182506  0.60052246 0.31251785]
   [0.5525696  0.4805326  0.4441876 ]
   [0.5340443  0.5781834  0.3184558 ]
   [0.6429912  0.5080738  0.522239  ]
   [0.6402109  0.56402624 0.5197626 ]
   [0.74398655 0.52049744 0.4017435 ]
   [0.7480644  0.5719653  0.60890007]
   [0.85161775 0.5248872  0.38791448]
   [0.8594842  0.5646565  0.43258464]]]]
[[[[0.47390026 0.5304462  0.23305696]
   [0.4713279  0.52133346 0.18798234]
   [0.46452042 0.5402044  0.29730088]
   [0.47369796 0.509809   0.5139663 ]
   [0.46495852 0.5473976  0.4421531 ]
   [0.5191174  0.4903446  0.42654133]
   [0.49798632 0.57561016 0.55431116]
   [0.5798795  0.47046897 0.29810292]
   [0.5271441  0.60423076 0.3340776 ]
   [0.560

[[[[0.4719027  0.54302573 0.27303556]
   [0.46608862 0.534855   0.2564897 ]
   [0.46728227 0.5449689  0.32838556]
   [0.46938163 0.5127144  0.45519242]
   [0.46963057 0.54848933 0.53773093]
   [0.512048   0.48663685 0.48693278]
   [0.515448   0.5810686  0.35263532]
   [0.5759592  0.4835989  0.2983157 ]
   [0.55494034 0.61793685 0.28448674]
   [0.582109   0.5042137  0.1553512 ]
   [0.5541885  0.60826266 0.2829552 ]
   [0.65859437 0.5194349  0.49185067]
   [0.65358025 0.57189494 0.56885374]
   [0.74433625 0.5236637  0.42862877]
   [0.7429502  0.5696179  0.55092967]
   [0.853654   0.52620053 0.40782863]
   [0.8555497  0.5631748  0.4717178 ]]]]
[[[[0.4705584  0.5426443  0.26247466]
   [0.464916   0.5345167  0.2534621 ]
   [0.4657144  0.54507947 0.3095109 ]
   [0.46929902 0.5127126  0.48202723]
   [0.46800256 0.54883605 0.533009  ]
   [0.51348746 0.4884612  0.5199971 ]
   [0.5129051  0.57969964 0.44324115]
   [0.57360774 0.48419642 0.29154238]
   [0.55593693 0.6177945  0.30597183]
   [0.578

[[[[0.45554158 0.5387207  0.25202248]
   [0.45069498 0.53500617 0.21959521]
   [0.4507566  0.5440141  0.34680784]
   [0.46047455 0.52254593 0.4510568 ]
   [0.45519668 0.5519631  0.5585594 ]
   [0.49862978 0.5003506  0.48156366]
   [0.48742843 0.58034146 0.56513417]
   [0.565029   0.4718408  0.30682448]
   [0.52356374 0.61339223 0.37858588]
   [0.55671436 0.48922595 0.3749077 ]
   [0.5449778  0.58916444 0.38419965]
   [0.635672   0.5123031  0.59170294]
   [0.6324569  0.5743421  0.62720525]
   [0.745485   0.5287746  0.57169044]
   [0.74623746 0.57318485 0.71793497]
   [0.852918   0.52976215 0.3795933 ]
   [0.8593917  0.5659519  0.52316004]]]]
[[[[0.45207238 0.5426786  0.2525298 ]
   [0.451423   0.54363686 0.26484457]
   [0.44786805 0.5473996  0.31237993]
   [0.45669708 0.5239229  0.42511332]
   [0.4538871  0.55328584 0.5378613 ]
   [0.4972844  0.5025792  0.46291545]
   [0.48547006 0.5771925  0.51195455]
   [0.5450854  0.47045583 0.29465988]
   [0.5133133  0.61233026 0.42611346]
   [0.550

[[[[0.45557964 0.5475653  0.38994697]
   [0.44790444 0.5500255  0.45747668]
   [0.4480533  0.5390861  0.42492288]
   [0.44866356 0.55270433 0.38913125]
   [0.452036   0.53215957 0.4926627 ]
   [0.49426764 0.56256264 0.4039151 ]
   [0.49137127 0.522306   0.4482232 ]
   [0.5591869  0.58941495 0.28338078]
   [0.55671585 0.50750345 0.19867143]
   [0.5565143  0.57086945 0.33554655]
   [0.55529773 0.54860115 0.28342947]
   [0.6411667  0.54128444 0.4293326 ]
   [0.64285517 0.5384601  0.48102048]
   [0.7344121  0.5427955  0.44551685]
   [0.73646104 0.5540149  0.40871537]
   [0.851074   0.5349069  0.39168847]
   [0.85234255 0.5483362  0.5515342 ]]]]
[[[[0.4497096  0.5522443  0.30342692]
   [0.4408947  0.55315816 0.39487568]
   [0.441555   0.5451703  0.38575745]
   [0.44159395 0.554861   0.31419578]
   [0.4447083  0.53800386 0.41369292]
   [0.49045894 0.5641136  0.401591  ]
   [0.49058586 0.5257485  0.45913792]
   [0.5539453  0.5859798  0.21912709]
   [0.55341554 0.50022835 0.2108121 ]
   [0.555

[[[[0.46204245 0.5346072  0.21641262]
   [0.4551301  0.5293887  0.17429705]
   [0.45760345 0.5435543  0.29986638]
   [0.46407032 0.5165994  0.4938237 ]
   [0.46034485 0.5531787  0.47809732]
   [0.5039159  0.4897614  0.551882  ]
   [0.5016602  0.58141476 0.5300013 ]
   [0.5725091  0.47251058 0.33030665]
   [0.56224436 0.61659235 0.35086194]
   [0.59215546 0.49170372 0.2923571 ]
   [0.6050859  0.6292568  0.40750682]
   [0.6526764  0.5183455  0.583783  ]
   [0.6504196  0.5784633  0.6307671 ]
   [0.74913085 0.52316594 0.427743  ]
   [0.7511264  0.57443076 0.6062989 ]
   [0.85806143 0.5225754  0.48552337]
   [0.86764646 0.5664805  0.47171474]]]]
[[[[0.4549836  0.5385945  0.24582675]
   [0.45355535 0.5361166  0.247009  ]
   [0.45212328 0.54551387 0.34187326]
   [0.45704302 0.52187437 0.35593927]
   [0.45613974 0.55375123 0.5638619 ]
   [0.4888568  0.4967334  0.5850551 ]
   [0.49131247 0.58290595 0.54933786]
   [0.5637222  0.4696206  0.36168322]
   [0.562817   0.62488824 0.3950326 ]
   [0.598

[[[[0.4583099  0.53646123 0.31714222]
   [0.45226675 0.53269994 0.22129922]
   [0.45147106 0.5445319  0.38250014]
   [0.45253795 0.5128888  0.45274726]
   [0.45352715 0.55123687 0.67252326]
   [0.4888863  0.48803684 0.5908346 ]
   [0.4863623  0.5785916  0.5939598 ]
   [0.54269314 0.4695599  0.30734518]
   [0.53812605 0.6136781  0.33283368]
   [0.5660584  0.50107193 0.22121957]
   [0.56908095 0.595181   0.34287062]
   [0.64001095 0.5162009  0.5911056 ]
   [0.63739556 0.5786229  0.6310379 ]
   [0.74292064 0.52423155 0.5886811 ]
   [0.7429668  0.574684   0.59345627]
   [0.8560814  0.5288035  0.38361776]
   [0.8645858  0.5699895  0.496648  ]]]]
[[[[0.44755512 0.5351252  0.29485708]
   [0.43864343 0.5312966  0.21093449]
   [0.44061965 0.5426222  0.2888451 ]
   [0.44179648 0.5186534  0.46432272]
   [0.4429617  0.54895866 0.5931537 ]
   [0.47669873 0.49000713 0.55849564]
   [0.47583506 0.57522726 0.56952083]
   [0.5471891  0.46809143 0.29882622]
   [0.5406338  0.61360055 0.37216544]
   [0.591

[[[[0.42684576 0.5321286  0.24956526]
   [0.42288917 0.5283073  0.23473166]
   [0.42230296 0.5349964  0.30282307]
   [0.42579624 0.5146097  0.505682  ]
   [0.42517996 0.5447902  0.62571347]
   [0.46392167 0.48672983 0.6331576 ]
   [0.46285266 0.57675564 0.652169  ]
   [0.54187953 0.47109425 0.26012027]
   [0.5338356  0.6046008  0.34901613]
   [0.5834152  0.50592667 0.23435166]
   [0.5820922  0.5895107  0.4013781 ]
   [0.6183724  0.5137229  0.5851828 ]
   [0.6155281  0.57236475 0.639367  ]
   [0.72040296 0.52398634 0.46475637]
   [0.7220396  0.57482314 0.5627588 ]
   [0.8405125  0.52949494 0.3619835 ]
   [0.8471463  0.56946313 0.5705503 ]]]]
[[[[0.42383108 0.5330758  0.25237212]
   [0.4146969  0.5295094  0.21030359]
   [0.41682982 0.54007995 0.27597085]
   [0.4190713  0.5182886  0.436916  ]
   [0.42044228 0.54763544 0.5621916 ]
   [0.4603792  0.49199045 0.5516567 ]
   [0.4627524  0.57519853 0.55839556]
   [0.5308598  0.4713881  0.44023654]
   [0.52555937 0.59925735 0.29333237]
   [0.562

[[[[0.4317263  0.5312696  0.27321377]
   [0.42337558 0.52643704 0.20517765]
   [0.42502147 0.5383949  0.38938892]
   [0.42644557 0.51423275 0.57089746]
   [0.4279877  0.5461874  0.68648493]
   [0.46815038 0.48586512 0.614478  ]
   [0.47032797 0.57325196 0.5952441 ]
   [0.53714824 0.46873236 0.37562448]
   [0.5291532  0.61708456 0.3467948 ]
   [0.54897416 0.4904593  0.34622198]
   [0.52713084 0.608377   0.40914074]
   [0.6139058  0.514731   0.5609242 ]
   [0.61384565 0.575212   0.6462307 ]
   [0.7151489  0.5227902  0.58917737]
   [0.71747637 0.57562363 0.57686913]
   [0.83450556 0.53310573 0.45169067]
   [0.83228153 0.5753759  0.53953004]]]]
[[[[0.43468285 0.54696214 0.2548737 ]
   [0.4269809  0.5353212  0.2431002 ]
   [0.4312027  0.54585826 0.37584776]
   [0.42856222 0.5185481  0.4775389 ]
   [0.43415016 0.5487736  0.6359678 ]
   [0.47185573 0.48908386 0.5577779 ]
   [0.47778517 0.5736693  0.5088357 ]
   [0.5379601  0.46585628 0.3737467 ]
   [0.53036416 0.6184558  0.3677263 ]
   [0.548

[[[[0.45283818 0.5463941  0.26179576]
   [0.44830784 0.5377704  0.2574527 ]
   [0.45005175 0.54816586 0.37489977]
   [0.44863173 0.5137543  0.46641132]
   [0.45224985 0.5479869  0.6816795 ]
   [0.47925627 0.47878247 0.5167872 ]
   [0.485161   0.56960404 0.5695323 ]
   [0.5401534  0.46262845 0.2972354 ]
   [0.535438   0.61109185 0.30747506]
   [0.5639054  0.5031168  0.21256422]
   [0.5515473  0.59360754 0.4297128 ]
   [0.63622606 0.50985515 0.57520014]
   [0.63603705 0.5742998  0.6490169 ]
   [0.743478   0.52233213 0.50363404]
   [0.74648285 0.5743083  0.6351657 ]
   [0.86243385 0.53195655 0.41830948]
   [0.8677062  0.5684991  0.47927824]]]]
[[[[0.4497407  0.54031545 0.34294784]
   [0.44222757 0.5348325  0.22571318]
   [0.44216067 0.5470345  0.33634755]
   [0.44463992 0.5132325  0.4401813 ]
   [0.44488597 0.54903704 0.6288088 ]
   [0.48089036 0.48177502 0.5626774 ]
   [0.482162   0.5725953  0.54165554]
   [0.54022527 0.46930057 0.3026325 ]
   [0.53506076 0.614228   0.3108152 ]
   [0.578

[[[[0.4283125  0.5358676  0.19124193]
   [0.424445   0.5300783  0.23969375]
   [0.42297325 0.5376788  0.32309237]
   [0.42676863 0.514335   0.6149406 ]
   [0.42616105 0.5461705  0.62515104]
   [0.46666753 0.48782155 0.59724027]
   [0.46231693 0.57336533 0.57154655]
   [0.5437303  0.47744346 0.37533376]
   [0.5275277  0.606482   0.4115281 ]
   [0.5776221  0.50756204 0.19230503]
   [0.56495345 0.5900227  0.3234551 ]
   [0.6198722  0.51719534 0.57812226]
   [0.6175486  0.5703473  0.638028  ]
   [0.71948475 0.53007853 0.53649086]
   [0.7230386  0.5763978  0.5156854 ]
   [0.83734983 0.53542346 0.38747543]
   [0.83624804 0.57367367 0.53143764]]]]
[[[[0.41926906 0.53760743 0.24868816]
   [0.41913947 0.5265777  0.27095544]
   [0.41517067 0.5381737  0.23790762]
   [0.4204627  0.5135989  0.49462074]
   [0.41994044 0.5460863  0.5513247 ]
   [0.4625365  0.48697722 0.5598918 ]
   [0.45983574 0.571964   0.46909884]
   [0.5370741  0.47431648 0.4064638 ]
   [0.5241065  0.60016    0.37224075]
   [0.567

[[[[0.44960505 0.54638267 0.21056464]
   [0.4468456  0.5353484  0.20885415]
   [0.44731826 0.5475265  0.2934897 ]
   [0.4475515  0.5151761  0.48779708]
   [0.44988307 0.5488591  0.64047   ]
   [0.48646355 0.4886006  0.60605407]
   [0.48979375 0.5731553  0.5547637 ]
   [0.5551984  0.47338456 0.34531572]
   [0.5499597  0.6316971  0.32008168]
   [0.5745047  0.49888322 0.22681011]
   [0.547068   0.61622804 0.38327736]
   [0.63658893 0.51618224 0.57095397]
   [0.6307353  0.5790966  0.5804546 ]
   [0.73299474 0.5250498  0.6700423 ]
   [0.729844   0.5749494  0.5839765 ]
   [0.84992385 0.53192383 0.40656516]
   [0.8511287  0.5720137  0.43539897]]]]
[[[[0.45423943 0.546374   0.22243066]
   [0.44989273 0.5345342  0.17345245]
   [0.45109564 0.5476827  0.3159249 ]
   [0.4511492  0.51074374 0.3344888 ]
   [0.4536804  0.5489615  0.6447451 ]
   [0.49027297 0.48654056 0.58639073]
   [0.49472386 0.57301044 0.5648375 ]
   [0.5579369  0.45755112 0.3754277 ]
   [0.55422306 0.6341055  0.31500933]
   [0.573

[[[[0.45007038 0.53693205 0.24450432]
   [0.44252563 0.5247207  0.12627016]
   [0.44341382 0.5378593  0.2807102 ]
   [0.4446056  0.51285243 0.34369728]
   [0.4436147  0.54521847 0.5554933 ]
   [0.4813745  0.4859882  0.5991063 ]
   [0.48168862 0.57097375 0.45201775]
   [0.5487812  0.48352492 0.28342184]
   [0.5404878  0.61212623 0.35901323]
   [0.6018232  0.5126027  0.26111427]
   [0.5877813  0.5830283  0.2981541 ]
   [0.6342571  0.51381356 0.6428038 ]
   [0.62857026 0.5703944  0.60306144]
   [0.7305803  0.5212985  0.55512774]
   [0.72868824 0.5723711  0.5299542 ]
   [0.85234135 0.53006536 0.4275112 ]
   [0.8478331  0.5683564  0.433598  ]]]]
[[[[0.4508619  0.53157365 0.2689358 ]
   [0.4424455  0.5281732  0.15827686]
   [0.44297907 0.53946185 0.33989504]
   [0.44359657 0.5157524  0.51668894]
   [0.44229805 0.5458052  0.61545396]
   [0.47988713 0.49136627 0.5816523 ]
   [0.4822966  0.56992996 0.47757357]
   [0.54933006 0.48527917 0.29640323]
   [0.5426535  0.60471416 0.37011573]
   [0.596

[[[[0.43390542 0.5438466  0.24904643]
   [0.42846143 0.53239036 0.23274997]
   [0.43066466 0.5436083  0.3799894 ]
   [0.4313589  0.5132107  0.5872458 ]
   [0.43525642 0.54554844 0.57968867]
   [0.46911305 0.48229355 0.5583813 ]
   [0.47221273 0.5691726  0.5329832 ]
   [0.5363408  0.4661362  0.36043707]
   [0.5268742  0.6074531  0.28860795]
   [0.55890703 0.50490475 0.24495575]
   [0.53785425 0.59467673 0.38658682]
   [0.6224899  0.51364815 0.5638783 ]
   [0.6205699  0.5713812  0.50336874]
   [0.7167945  0.52058476 0.46470243]
   [0.72215724 0.57091206 0.53141606]
   [0.82954454 0.53375196 0.44716975]
   [0.8273907  0.5660113  0.5691328 ]]]]
[[[[0.44889674 0.53908634 0.27849334]
   [0.438133   0.5328677  0.21156538]
   [0.44238192 0.5428488  0.35248694]
   [0.44072717 0.51182175 0.45217493]
   [0.44431326 0.5447357  0.523193  ]
   [0.47379988 0.48460853 0.44606742]
   [0.48077735 0.5708662  0.45447206]
   [0.5318917  0.4606106  0.31738892]
   [0.52516675 0.61791825 0.29964778]
   [0.534

[[[[0.45271218 0.5523323  0.22406416]
   [0.441513   0.54037356 0.20619498]
   [0.44594622 0.55567276 0.22623385]
   [0.4433062  0.5194639  0.40836564]
   [0.44962376 0.5563225  0.48419967]
   [0.47695428 0.4897011  0.47417164]
   [0.48647946 0.5777217  0.4474419 ]
   [0.541564   0.46851128 0.29151392]
   [0.5303664  0.6212834  0.36245826]
   [0.5484701  0.50361896 0.21501066]
   [0.5270275  0.61370474 0.46744546]
   [0.63030666 0.5166687  0.52408373]
   [0.629061   0.5778864  0.5504568 ]
   [0.72588843 0.52216476 0.5610082 ]
   [0.72617364 0.57432127 0.57686955]
   [0.8387868  0.53054315 0.369077  ]
   [0.83982205 0.575256   0.52833915]]]]
[[[[0.4519752  0.5537624  0.18144414]
   [0.4457916  0.5371829  0.18837814]
   [0.44805956 0.5551051  0.21846059]
   [0.44817683 0.51660943 0.553689  ]
   [0.4517052  0.55580986 0.53538173]
   [0.48292753 0.48742622 0.52683777]
   [0.4888283  0.5764173  0.4151944 ]
   [0.5487639  0.46129042 0.35458884]
   [0.5351216  0.6262924  0.3236883 ]
   [0.562

[[[[0.4427935  0.53355265 0.23343049]
   [0.4378562  0.52879465 0.21440841]
   [0.4361143  0.54249847 0.21897045]
   [0.43844062 0.5140954  0.50240004]
   [0.43974954 0.55122197 0.5336031 ]
   [0.47570437 0.48473877 0.5254073 ]
   [0.48094746 0.57720226 0.5434078 ]
   [0.54445136 0.46786782 0.33043742]
   [0.54201245 0.6184672  0.321628  ]
   [0.5743405  0.5014649  0.2553062 ]
   [0.5696184  0.59459573 0.4282188 ]
   [0.6323978  0.5109062  0.6243973 ]
   [0.63137364 0.5744339  0.62857234]
   [0.73871267 0.5193794  0.55487573]
   [0.7389208  0.573923   0.61689997]
   [0.85964245 0.5278751  0.4092181 ]
   [0.86695135 0.5702971  0.45931175]]]]
[[[[0.44126412 0.5385474  0.28090084]
   [0.43783796 0.5273695  0.22339612]
   [0.43903524 0.53868926 0.37119022]
   [0.43686628 0.52060205 0.51105845]
   [0.43806088 0.550878   0.52168226]
   [0.47595924 0.4928741  0.5662476 ]
   [0.47623813 0.5748433  0.63399136]
   [0.55029327 0.4751261  0.29606313]
   [0.5455291  0.6163853  0.36515468]
   [0.598

[[[[0.41993684 0.5294019  0.3036322 ]
   [0.4137728  0.5222782  0.2809158 ]
   [0.41675338 0.5328499  0.3492403 ]
   [0.41735727 0.50579107 0.49155837]
   [0.41837224 0.54385763 0.48313957]
   [0.4602977  0.47931275 0.5486177 ]
   [0.46104038 0.57469463 0.52998376]
   [0.5405319  0.46598476 0.40304947]
   [0.5178759  0.6104232  0.3991877 ]
   [0.5545467  0.4971516  0.37886995]
   [0.54779667 0.58662367 0.39725235]
   [0.61852247 0.51587987 0.568122  ]
   [0.6197031  0.5720982  0.6579988 ]
   [0.7245014  0.5221834  0.54774404]
   [0.72786295 0.57432866 0.5427946 ]
   [0.8347224  0.5374309  0.4067317 ]
   [0.82897544 0.56980956 0.5414799 ]]]]
[[[[0.43098542 0.5394956  0.30097175]
   [0.42186806 0.5270998  0.25891006]
   [0.42325982 0.53954446 0.36114028]
   [0.4254317  0.51244015 0.5505816 ]
   [0.426352   0.5452049  0.54977727]
   [0.47023845 0.48351204 0.5373253 ]
   [0.46824992 0.57329154 0.553185  ]
   [0.5402248  0.4731809  0.38154918]
   [0.52752167 0.6047307  0.4034191 ]
   [0.545

[[[[0.43276963 0.53447187 0.22264728]
   [0.42808378 0.52591    0.25238174]
   [0.43059668 0.5349697  0.3548211 ]
   [0.43115863 0.5038831  0.454761  ]
   [0.43405485 0.5415617  0.57981   ]
   [0.47403035 0.48166105 0.46442923]
   [0.47909778 0.57229125 0.5465055 ]
   [0.5387467  0.45587206 0.3351224 ]
   [0.53249633 0.6245487  0.25926077]
   [0.5445504  0.48528528 0.2578902 ]
   [0.52457213 0.6019035  0.3708014 ]
   [0.6290478  0.51270473 0.55850923]
   [0.62811136 0.5727649  0.5675762 ]
   [0.7374748  0.5220927  0.6564286 ]
   [0.7399005  0.5754102  0.6710428 ]
   [0.8612318  0.53314334 0.48683843]
   [0.86608255 0.57104886 0.51476884]]]]
[[[[0.43881828 0.53466296 0.25380066]
   [0.4288691  0.52480096 0.2045658 ]
   [0.43382776 0.5386834  0.37645784]
   [0.43077993 0.5043993  0.42391202]
   [0.43622077 0.54458517 0.62449527]
   [0.470559   0.4769983  0.42379543]
   [0.4787466  0.57394916 0.36619803]
   [0.54719687 0.4432443  0.27675915]
   [0.53551733 0.62635404 0.32276085]
   [0.562

In [10]:
frame.shape

(480, 640, 3)

In [ ]:
left_elbow = keypoints_with_scores[0][0][7]

In [ ]:
left_elbow

In [ ]:
np.array(left_elbow[:2]*[480,640]).astype(int)

# Draw Keypoints 

In [6]:
def draw_keypoints(frame, keypoints, confidence_threshold):
    y,x,c = frame.shape
    shaped = np.squeeze(np.multiply(keypoints,[y,x,1]))
    
    for kp in shaped: 
        ky,kx, kp_conf = kp
        
        if kp_conf >confidence_threshold:
            
            cv2.circle(frame, (int(kx), int(ky)),4,(0,0,255),-1)

# Draw Edges:



In [8]:
EDGES ={
    (0, 1): 'm',
    (0, 2): 'c',
    (1, 3): 'm',
    (2, 4): 'c',
    (0, 5): 'm',
    (0, 6): 'c',
    (5, 7): 'm',
    (7, 9): 'm',
    (6, 8): 'm',
    (8, 10): 'c',
    (5, 6): 'y',
    (5, 11): 'm',
    (6, 12): 'c',
    (11, 12): 'y',
    (11, 13): 'm',
    (13, 15): 'm',
    (12, 14): 'c',
    (14, 16): 'c'
}

In [7]:
def draw_connections(frame, keypoints, edges, confidence_threshold):
    y,x,c = frame.shape
    
    shaped = np.squeeze(np.multiply(keypoints,[y,x,1]))
    
    for edge, color in edges.items():
        
        p1,p2 = edge
        y1,x1,c1 = shaped[p1]
        y2,x2,c2 = shaped[p2]        
        
        if (c1> confidence_threshold) & (c2> confidence_threshold):
            cv2.line(frame, (int(x1), int(y1)), (int(x2), int(y2)), (0,255,0), 2)


# using my own video now 



In [20]:
model = hub.load('https://tfhub.dev/google/movenet/multipose/lightning/1')
movenet = model.signatures['serving_default']

OSError: SavedModel file does not exist at: C:\Users\ayush\AppData\Local\Temp\tfhub_modules\312f001449331ee3d410d758fccdc9945a65dbc3\{saved_model.pbtxt|saved_model.pb}

In [19]:
def loop_through_people(frame, keypoints_with_scores, edges, confidence_threshold):
    for person in keypoints_with_scores:
        draw_connections(frame, person, edges, confidence_threshold)
        draw_keypoints(frame, person, confidence_threshold)

In [ ]:
cap = cv2.VideoCapture(0)
while cap.isOpened():
    ret, frame = cap.read()
    
    # Resize image
    img = frame.copy()
    img = tf.image.resize_with_pad(tf.expand_dims(img, axis=0), 640,480)
    input_img = tf.cast(img, dtype=tf.int32)
    
    # Detection section
    results = movenet(input_img)
    keypoints_with_scores = results['output_0'].numpy()[:,:,:51].reshape((6,17,3))
    
    # Render keypoints 
    loop_through_people(frame, keypoints_with_scores, EDGES, 0.2)
    
    cv2.imshow('Movenet Multipose', frame)
    
    if cv2.waitKey(2) & 0xFF==ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

# These models above and below are made using the movenet multiple people detection model 

### Therefore would give varied results hence extra care is reuqired in handling them

In [ ]:
cap = cv2.VideoCapture('JumpRopeChairAngleJUMPS.mp4')
while cap.isOpened():
    ret, frame = cap.read()
    
    # Resize image
    img = frame.copy()
    img = tf.image.resize_with_pad(tf.expand_dims(img, axis=0), 640,480)
    input_img = tf.cast(img, dtype=tf.int32)
    
    # Detection section
    results = movenet(input_img)
    keypoints_with_scores = results['output_0'].numpy()[:,:,:51].reshape((6,17,3))
    
    # Render keypoints 
    loop_through_people(frame, keypoints_with_scores, EDGES, 0.3)
    
    cv2.imshow('Movenet Multipose', frame)
    
    if cv2.waitKey(2) & 0xFF==ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

In [ ]:
frame.shape